// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: hostapi.proto

// Plugin -> host RPCs: mirrors the api.HostAPI interface and its RPC
// Args/Reply structs one-to-one so the mapping stays easy to cross-reference.
//
// IMPORTANT: field numbers must never be renumbered or reused once released.
// Host and plugin(s) are deployed independently, so wire compatibility across
// versions depends entirely on additive changes (new fields get new numbers).

package hostapipb

import (
	context "context"
	commonpb "github.com/seatsurfing/seatsurfing/server/api/commonpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostAPIService_SettingsGet_FullMethodName                    = "/seatsurfing.plugin.v1.HostAPIService/SettingsGet"
	HostAPIService_SettingsGetBool_FullMethodName                = "/seatsurfing.plugin.v1.HostAPIService/SettingsGetBool"
	HostAPIService_SettingsGetInt_FullMethodName                 = "/seatsurfing.plugin.v1.HostAPIService/SettingsGetInt"
	HostAPIService_SettingsGetNullUUID_FullMethodName            = "/seatsurfing.plugin.v1.HostAPIService/SettingsGetNullUUID"
	HostAPIService_SettingsGetOrgIDsByValue_FullMethodName       = "/seatsurfing.plugin.v1.HostAPIService/SettingsGetOrgIDsByValue"
	HostAPIService_SettingsSet_FullMethodName                    = "/seatsurfing.plugin.v1.HostAPIService/SettingsSet"
	HostAPIService_SettingsDelete_FullMethodName                 = "/seatsurfing.plugin.v1.HostAPIService/SettingsDelete"
	HostAPIService_UserGetOne_FullMethodName                     = "/seatsurfing.plugin.v1.HostAPIService/UserGetOne"
	HostAPIService_UserGetAll_FullMethodName                     = "/seatsurfing.plugin.v1.HostAPIService/UserGetAll"
	HostAPIService_UserGetByEmail_FullMethodName                 = "/seatsurfing.plugin.v1.HostAPIService/UserGetByEmail"
	HostAPIService_UserGetCount_FullMethodName                   = "/seatsurfing.plugin.v1.HostAPIService/UserGetCount"
	HostAPIService_UserGetHashedPassword_FullMethodName          = "/seatsurfing.plugin.v1.HostAPIService/UserGetHashedPassword"
	HostAPIService_UserGetUsersWithEmail_FullMethodName          = "/seatsurfing.plugin.v1.HostAPIService/UserGetUsersWithEmail"
	HostAPIService_UserIsOrgAdmin_FullMethodName                 = "/seatsurfing.plugin.v1.HostAPIService/UserIsOrgAdmin"
	HostAPIService_UserIsSuperAdmin_FullMethodName               = "/seatsurfing.plugin.v1.HostAPIService/UserIsSuperAdmin"
	HostAPIService_UserCreate_FullMethodName                     = "/seatsurfing.plugin.v1.HostAPIService/UserCreate"
	HostAPIService_UserUpdate_FullMethodName                     = "/seatsurfing.plugin.v1.HostAPIService/UserUpdate"
	HostAPIService_UserDelete_FullMethodName                     = "/seatsurfing.plugin.v1.HostAPIService/UserDelete"
	HostAPIService_OrgGetOne_FullMethodName                      = "/seatsurfing.plugin.v1.HostAPIService/OrgGetOne"
	HostAPIService_OrgGetAll_FullMethodName                      = "/seatsurfing.plugin.v1.HostAPIService/OrgGetAll"
	HostAPIService_OrgGetOneByDomain_FullMethodName              = "/seatsurfing.plugin.v1.HostAPIService/OrgGetOneByDomain"
	HostAPIService_OrgGetByEmail_FullMethodName                  = "/seatsurfing.plugin.v1.HostAPIService/OrgGetByEmail"
	HostAPIService_OrgGetAllDaysPassedSinceSignup_FullMethodName = "/seatsurfing.plugin.v1.HostAPIService/OrgGetAllDaysPassedSinceSignup"
	HostAPIService_OrgGetPrimaryDomain_FullMethodName            = "/seatsurfing.plugin.v1.HostAPIService/OrgGetPrimaryDomain"
	HostAPIService_OrgCreate_FullMethodName                      = "/seatsurfing.plugin.v1.HostAPIService/OrgCreate"
	HostAPIService_OrgUpdate_FullMethodName                      = "/seatsurfing.plugin.v1.HostAPIService/OrgUpdate"
	HostAPIService_OrgDelete_FullMethodName                      = "/seatsurfing.plugin.v1.HostAPIService/OrgDelete"
	HostAPIService_OrgAddDomain_FullMethodName                   = "/seatsurfing.plugin.v1.HostAPIService/OrgAddDomain"
	HostAPIService_OrgSetPrimaryDomain_FullMethodName            = "/seatsurfing.plugin.v1.HostAPIService/OrgSetPrimaryDomain"
	HostAPIService_OrgCreateSampleData_FullMethodName            = "/seatsurfing.plugin.v1.HostAPIService/OrgCreateSampleData"
	HostAPIService_GroupGetOne_FullMethodName                    = "/seatsurfing.plugin.v1.HostAPIService/GroupGetOne"
	HostAPIService_GroupGetAll_FullMethodName                    = "/seatsurfing.plugin.v1.HostAPIService/GroupGetAll"
	HostAPIService_GroupGetByName_FullMethodName                 = "/seatsurfing.plugin.v1.HostAPIService/GroupGetByName"
	HostAPIService_GroupGetMemberUserIDs_FullMethodName          = "/seatsurfing.plugin.v1.HostAPIService/GroupGetMemberUserIDs"
	HostAPIService_GroupAddMembers_FullMethodName                = "/seatsurfing.plugin.v1.HostAPIService/GroupAddMembers"
	HostAPIService_GroupRemoveMembers_FullMethodName             = "/seatsurfing.plugin.v1.HostAPIService/GroupRemoveMembers"
	HostAPIService_GroupCreate_FullMethodName                    = "/seatsurfing.plugin.v1.HostAPIService/GroupCreate"
	HostAPIService_GroupUpdate_FullMethodName                    = "/seatsurfing.plugin.v1.HostAPIService/GroupUpdate"
	HostAPIService_GroupDelete_FullMethodName                    = "/seatsurfing.plugin.v1.HostAPIService/GroupDelete"
	HostAPIService_BookingGetOne_FullMethodName                  = "/seatsurfing.plugin.v1.HostAPIService/BookingGetOne"
	HostAPIService_SpaceGetOne_FullMethodName                    = "/seatsurfing.plugin.v1.HostAPIService/SpaceGetOne"
	HostAPIService_SpaceGetCount_FullMethodName                  = "/seatsurfing.plugin.v1.HostAPIService/SpaceGetCount"
	HostAPIService_LocationGetOne_FullMethodName                 = "/seatsurfing.plugin.v1.HostAPIService/LocationGetOne"
	HostAPIService_LocationGetCount_FullMethodName               = "/seatsurfing.plugin.v1.HostAPIService/LocationGetCount"
	HostAPIService_LocationGetTimezone_FullMethodName            = "/seatsurfing.plugin.v1.HostAPIService/LocationGetTimezone"
	HostAPIService_AuthProviderCreate_FullMethodName             = "/seatsurfing.plugin.v1.HostAPIService/AuthProviderCreate"
	HostAPIService_AuthProviderUpdate_FullMethodName             = "/seatsurfing.plugin.v1.HostAPIService/AuthProviderUpdate"
	HostAPIService_AuthStateCreate_FullMethodName                = "/seatsurfing.plugin.v1.HostAPIService/AuthStateCreate"
	HostAPIService_SendEmail_FullMethodName                      = "/seatsurfing.plugin.v1.HostAPIService/SendEmail"
	HostAPIService_Encrypt_FullMethodName                        = "/seatsurfing.plugin.v1.HostAPIService/Encrypt"
	HostAPIService_Decrypt_FullMethodName                        = "/seatsurfing.plugin.v1.HostAPIService/Decrypt"
	HostAPIService_IsValidLanguageCode_FullMethodName            = "/seatsurfing.plugin.v1.HostAPIService/IsValidLanguageCode"
	HostAPIService_DisablePasswordLogin_FullMethodName           = "/seatsurfing.plugin.v1.HostAPIService/DisablePasswordLogin"
	HostAPIService_FormatPublicURL_FullMethodName                = "/seatsurfing.plugin.v1.HostAPIService/FormatPublicURL"
	HostAPIService_IsDevelopmentMode_FullMethodName              = "/seatsurfing.plugin.v1.HostAPIService/IsDevelopmentMode"
	HostAPIService_GetPostgresURL_FullMethodName                 = "/seatsurfing.plugin.v1.HostAPIService/GetPostgresURL"
)

// HostAPIServiceClient is the client API for HostAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostAPIServiceClient interface {
	// Settings
	SettingsGet(ctx context.Context, in *SettingsGetArgs, opts ...grpc.CallOption) (*SettingsGetReply, error)
	SettingsGetBool(ctx context.Context, in *SettingsGetArgs, opts ...grpc.CallOption) (*SettingsGetBoolReply, error)
	SettingsGetInt(ctx context.Context, in *SettingsGetArgs, opts ...grpc.CallOption) (*IntReply, error)
	SettingsGetNullUUID(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*StringReply, error)
	SettingsGetOrgIDsByValue(ctx context.Context, in *SettingsGetOrgIDsArgs, opts ...grpc.CallOption) (*StringSliceReply, error)
	SettingsSet(ctx context.Context, in *SettingsSetArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	SettingsDelete(ctx context.Context, in *SettingsDeleteArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	// Users
	UserGetOne(ctx context.Context, in *UserGetOneArgs, opts ...grpc.CallOption) (*UserGetOneReply, error)
	UserGetAll(ctx context.Context, in *UserGetAllArgs, opts ...grpc.CallOption) (*UserGetAllReply, error)
	UserGetByEmail(ctx context.Context, in *UserGetByEmailArgs, opts ...grpc.CallOption) (*UserGetOneReply, error)
	UserGetCount(ctx context.Context, in *UserGetCountArgs, opts ...grpc.CallOption) (*IntReply, error)
	UserGetHashedPassword(ctx context.Context, in *UserHashPasswordArgs, opts ...grpc.CallOption) (*StringReply, error)
	UserGetUsersWithEmail(ctx context.Context, in *UserGetUsersWithEmailArgs, opts ...grpc.CallOption) (*UserGetUsersWithEmailReply, error)
	UserIsOrgAdmin(ctx context.Context, in *UserIsAdminArgs, opts ...grpc.CallOption) (*BoolReply, error)
	UserIsSuperAdmin(ctx context.Context, in *UserIsAdminArgs, opts ...grpc.CallOption) (*BoolReply, error)
	UserCreate(ctx context.Context, in *UserMutateArgs, opts ...grpc.CallOption) (*UserGetOneReply, error)
	UserUpdate(ctx context.Context, in *UserMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	UserDelete(ctx context.Context, in *UserMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	// Organizations
	OrgGetOne(ctx context.Context, in *OrgGetOneArgs, opts ...grpc.CallOption) (*OrgGetOneReply, error)
	OrgGetAll(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*OrgGetAllReply, error)
	OrgGetOneByDomain(ctx context.Context, in *OrgGetByDomainArgs, opts ...grpc.CallOption) (*OrgGetOneReply, error)
	OrgGetByEmail(ctx context.Context, in *OrgGetByEmailArgs, opts ...grpc.CallOption) (*OrgGetOneReply, error)
	OrgGetAllDaysPassedSinceSignup(ctx context.Context, in *OrgGetDaysPassedArgs, opts ...grpc.CallOption) (*OrgGetAllReply, error)
	OrgGetPrimaryDomain(ctx context.Context, in *OrgGetPrimaryDomainArgs, opts ...grpc.CallOption) (*OrgGetPrimaryDomainReply, error)
	OrgCreate(ctx context.Context, in *OrgMutateArgs, opts ...grpc.CallOption) (*OrgGetOneReply, error)
	OrgUpdate(ctx context.Context, in *OrgMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	OrgDelete(ctx context.Context, in *OrgMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	OrgAddDomain(ctx context.Context, in *OrgAddDomainArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	OrgSetPrimaryDomain(ctx context.Context, in *OrgSetPrimaryDomainArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	OrgCreateSampleData(ctx context.Context, in *OrgCreateSampleDataArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	// Groups
	GroupGetOne(ctx context.Context, in *GroupGetOneArgs, opts ...grpc.CallOption) (*GroupGetOneReply, error)
	GroupGetAll(ctx context.Context, in *GroupGetAllArgs, opts ...grpc.CallOption) (*GroupGetAllReply, error)
	GroupGetByName(ctx context.Context, in *GroupGetByNameArgs, opts ...grpc.CallOption) (*GroupGetOneReply, error)
	GroupGetMemberUserIDs(ctx context.Context, in *GroupGetMemberIDsArgs, opts ...grpc.CallOption) (*GroupGetMemberIDsReply, error)
	GroupAddMembers(ctx context.Context, in *GroupMembersArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	GroupRemoveMembers(ctx context.Context, in *GroupMembersArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	GroupCreate(ctx context.Context, in *GroupMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	GroupUpdate(ctx context.Context, in *GroupMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	GroupDelete(ctx context.Context, in *GroupMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	// Bookings
	BookingGetOne(ctx context.Context, in *BookingGetOneArgs, opts ...grpc.CallOption) (*BookingGetOneReply, error)
	// Spaces
	SpaceGetOne(ctx context.Context, in *SpaceGetOneArgs, opts ...grpc.CallOption) (*SpaceGetOneReply, error)
	SpaceGetCount(ctx context.Context, in *SpaceGetCountArgs, opts ...grpc.CallOption) (*IntReply, error)
	// Locations
	LocationGetOne(ctx context.Context, in *LocationGetOneArgs, opts ...grpc.CallOption) (*LocationGetOneReply, error)
	LocationGetCount(ctx context.Context, in *LocationGetCountArgs, opts ...grpc.CallOption) (*IntReply, error)
	LocationGetTimezone(ctx context.Context, in *LocationGetTimezoneArgs, opts ...grpc.CallOption) (*StringReply, error)
	// AuthProvider
	AuthProviderCreate(ctx context.Context, in *AuthProviderMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	AuthProviderUpdate(ctx context.Context, in *AuthProviderMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	// AuthState
	AuthStateCreate(ctx context.Context, in *AuthStateMutateArgs, opts ...grpc.CallOption) (*AuthStateGetOneReply, error)
	// General
	SendEmail(ctx context.Context, in *SendEmailArgs, opts ...grpc.CallOption) (*ErrorReply, error)
	Encrypt(ctx context.Context, in *EncryptArgs, opts ...grpc.CallOption) (*EncryptReply, error)
	Decrypt(ctx context.Context, in *DecryptArgs, opts ...grpc.CallOption) (*EncryptReply, error)
	IsValidLanguageCode(ctx context.Context, in *IsValidLangArgs, opts ...grpc.CallOption) (*BoolReply, error)
	DisablePasswordLogin(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*BoolReply, error)
	FormatPublicURL(ctx context.Context, in *FormatPublicURLArgs, opts ...grpc.CallOption) (*StringReply, error)
	IsDevelopmentMode(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*BoolReply, error)
	GetPostgresURL(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*StringReply, error)
}

type hostAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostAPIServiceClient(cc grpc.ClientConnInterface) HostAPIServiceClient {
	return &hostAPIServiceClient{cc}
}

func (c *hostAPIServiceClient) SettingsGet(ctx context.Context, in *SettingsGetArgs, opts ...grpc.CallOption) (*SettingsGetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsGetReply)
	err := c.cc.Invoke(ctx, HostAPIService_SettingsGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) SettingsGetBool(ctx context.Context, in *SettingsGetArgs, opts ...grpc.CallOption) (*SettingsGetBoolReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsGetBoolReply)
	err := c.cc.Invoke(ctx, HostAPIService_SettingsGetBool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) SettingsGetInt(ctx context.Context, in *SettingsGetArgs, opts ...grpc.CallOption) (*IntReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntReply)
	err := c.cc.Invoke(ctx, HostAPIService_SettingsGetInt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) SettingsGetNullUUID(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*StringReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringReply)
	err := c.cc.Invoke(ctx, HostAPIService_SettingsGetNullUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) SettingsGetOrgIDsByValue(ctx context.Context, in *SettingsGetOrgIDsArgs, opts ...grpc.CallOption) (*StringSliceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringSliceReply)
	err := c.cc.Invoke(ctx, HostAPIService_SettingsGetOrgIDsByValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) SettingsSet(ctx context.Context, in *SettingsSetArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_SettingsSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) SettingsDelete(ctx context.Context, in *SettingsDeleteArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_SettingsDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserGetOne(ctx context.Context, in *UserGetOneArgs, opts ...grpc.CallOption) (*UserGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserGetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserGetAll(ctx context.Context, in *UserGetAllArgs, opts ...grpc.CallOption) (*UserGetAllReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetAllReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserGetByEmail(ctx context.Context, in *UserGetByEmailArgs, opts ...grpc.CallOption) (*UserGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserGetByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserGetCount(ctx context.Context, in *UserGetCountArgs, opts ...grpc.CallOption) (*IntReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserGetCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserGetHashedPassword(ctx context.Context, in *UserHashPasswordArgs, opts ...grpc.CallOption) (*StringReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserGetHashedPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserGetUsersWithEmail(ctx context.Context, in *UserGetUsersWithEmailArgs, opts ...grpc.CallOption) (*UserGetUsersWithEmailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetUsersWithEmailReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserGetUsersWithEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserIsOrgAdmin(ctx context.Context, in *UserIsAdminArgs, opts ...grpc.CallOption) (*BoolReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserIsOrgAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserIsSuperAdmin(ctx context.Context, in *UserIsAdminArgs, opts ...grpc.CallOption) (*BoolReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserIsSuperAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserCreate(ctx context.Context, in *UserMutateArgs, opts ...grpc.CallOption) (*UserGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserUpdate(ctx context.Context, in *UserMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) UserDelete(ctx context.Context, in *UserMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_UserDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgGetOne(ctx context.Context, in *OrgGetOneArgs, opts ...grpc.CallOption) (*OrgGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgGetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgGetAll(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*OrgGetAllReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgGetAllReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgGetOneByDomain(ctx context.Context, in *OrgGetByDomainArgs, opts ...grpc.CallOption) (*OrgGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgGetOneByDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgGetByEmail(ctx context.Context, in *OrgGetByEmailArgs, opts ...grpc.CallOption) (*OrgGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgGetByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgGetAllDaysPassedSinceSignup(ctx context.Context, in *OrgGetDaysPassedArgs, opts ...grpc.CallOption) (*OrgGetAllReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgGetAllReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgGetAllDaysPassedSinceSignup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgGetPrimaryDomain(ctx context.Context, in *OrgGetPrimaryDomainArgs, opts ...grpc.CallOption) (*OrgGetPrimaryDomainReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgGetPrimaryDomainReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgGetPrimaryDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgCreate(ctx context.Context, in *OrgMutateArgs, opts ...grpc.CallOption) (*OrgGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgUpdate(ctx context.Context, in *OrgMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgDelete(ctx context.Context, in *OrgMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgAddDomain(ctx context.Context, in *OrgAddDomainArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgAddDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgSetPrimaryDomain(ctx context.Context, in *OrgSetPrimaryDomainArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgSetPrimaryDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) OrgCreateSampleData(ctx context.Context, in *OrgCreateSampleDataArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_OrgCreateSampleData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) GroupGetOne(ctx context.Context, in *GroupGetOneArgs, opts ...grpc.CallOption) (*GroupGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_GroupGetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) GroupGetAll(ctx context.Context, in *GroupGetAllArgs, opts ...grpc.CallOption) (*GroupGetAllReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupGetAllReply)
	err := c.cc.Invoke(ctx, HostAPIService_GroupGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) GroupGetByName(ctx context.Context, in *GroupGetByNameArgs, opts ...grpc.CallOption) (*GroupGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_GroupGetByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) GroupGetMemberUserIDs(ctx context.Context, in *GroupGetMemberIDsArgs, opts ...grpc.CallOption) (*GroupGetMemberIDsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupGetMemberIDsReply)
	err := c.cc.Invoke(ctx, HostAPIService_GroupGetMemberUserIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) GroupAddMembers(ctx context.Context, in *GroupMembersArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_GroupAddMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) GroupRemoveMembers(ctx context.Context, in *GroupMembersArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_GroupRemoveMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) GroupCreate(ctx context.Context, in *GroupMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_GroupCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) GroupUpdate(ctx context.Context, in *GroupMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_GroupUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) GroupDelete(ctx context.Context, in *GroupMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_GroupDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) BookingGetOne(ctx context.Context, in *BookingGetOneArgs, opts ...grpc.CallOption) (*BookingGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_BookingGetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) SpaceGetOne(ctx context.Context, in *SpaceGetOneArgs, opts ...grpc.CallOption) (*SpaceGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpaceGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_SpaceGetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) SpaceGetCount(ctx context.Context, in *SpaceGetCountArgs, opts ...grpc.CallOption) (*IntReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntReply)
	err := c.cc.Invoke(ctx, HostAPIService_SpaceGetCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) LocationGetOne(ctx context.Context, in *LocationGetOneArgs, opts ...grpc.CallOption) (*LocationGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocationGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_LocationGetOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) LocationGetCount(ctx context.Context, in *LocationGetCountArgs, opts ...grpc.CallOption) (*IntReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntReply)
	err := c.cc.Invoke(ctx, HostAPIService_LocationGetCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) LocationGetTimezone(ctx context.Context, in *LocationGetTimezoneArgs, opts ...grpc.CallOption) (*StringReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringReply)
	err := c.cc.Invoke(ctx, HostAPIService_LocationGetTimezone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) AuthProviderCreate(ctx context.Context, in *AuthProviderMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_AuthProviderCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) AuthProviderUpdate(ctx context.Context, in *AuthProviderMutateArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_AuthProviderUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) AuthStateCreate(ctx context.Context, in *AuthStateMutateArgs, opts ...grpc.CallOption) (*AuthStateGetOneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthStateGetOneReply)
	err := c.cc.Invoke(ctx, HostAPIService_AuthStateCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) SendEmail(ctx context.Context, in *SendEmailArgs, opts ...grpc.CallOption) (*ErrorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorReply)
	err := c.cc.Invoke(ctx, HostAPIService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) Encrypt(ctx context.Context, in *EncryptArgs, opts ...grpc.CallOption) (*EncryptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptReply)
	err := c.cc.Invoke(ctx, HostAPIService_Encrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) Decrypt(ctx context.Context, in *DecryptArgs, opts ...grpc.CallOption) (*EncryptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptReply)
	err := c.cc.Invoke(ctx, HostAPIService_Decrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) IsValidLanguageCode(ctx context.Context, in *IsValidLangArgs, opts ...grpc.CallOption) (*BoolReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, HostAPIService_IsValidLanguageCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) DisablePasswordLogin(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*BoolReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, HostAPIService_DisablePasswordLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) FormatPublicURL(ctx context.Context, in *FormatPublicURLArgs, opts ...grpc.CallOption) (*StringReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringReply)
	err := c.cc.Invoke(ctx, HostAPIService_FormatPublicURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) IsDevelopmentMode(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*BoolReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, HostAPIService_IsDevelopmentMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIServiceClient) GetPostgresURL(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*StringReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringReply)
	err := c.cc.Invoke(ctx, HostAPIService_GetPostgresURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostAPIServiceServer is the server API for HostAPIService service.
// All implementations must embed UnimplementedHostAPIServiceServer
// for forward compatibility.
type HostAPIServiceServer interface {
	// Settings
	SettingsGet(context.Context, *SettingsGetArgs) (*SettingsGetReply, error)
	SettingsGetBool(context.Context, *SettingsGetArgs) (*SettingsGetBoolReply, error)
	SettingsGetInt(context.Context, *SettingsGetArgs) (*IntReply, error)
	SettingsGetNullUUID(context.Context, *commonpb.Empty) (*StringReply, error)
	SettingsGetOrgIDsByValue(context.Context, *SettingsGetOrgIDsArgs) (*StringSliceReply, error)
	SettingsSet(context.Context, *SettingsSetArgs) (*ErrorReply, error)
	SettingsDelete(context.Context, *SettingsDeleteArgs) (*ErrorReply, error)
	// Users
	UserGetOne(context.Context, *UserGetOneArgs) (*UserGetOneReply, error)
	UserGetAll(context.Context, *UserGetAllArgs) (*UserGetAllReply, error)
	UserGetByEmail(context.Context, *UserGetByEmailArgs) (*UserGetOneReply, error)
	UserGetCount(context.Context, *UserGetCountArgs) (*IntReply, error)
	UserGetHashedPassword(context.Context, *UserHashPasswordArgs) (*StringReply, error)
	UserGetUsersWithEmail(context.Context, *UserGetUsersWithEmailArgs) (*UserGetUsersWithEmailReply, error)
	UserIsOrgAdmin(context.Context, *UserIsAdminArgs) (*BoolReply, error)
	UserIsSuperAdmin(context.Context, *UserIsAdminArgs) (*BoolReply, error)
	UserCreate(context.Context, *UserMutateArgs) (*UserGetOneReply, error)
	UserUpdate(context.Context, *UserMutateArgs) (*ErrorReply, error)
	UserDelete(context.Context, *UserMutateArgs) (*ErrorReply, error)
	// Organizations
	OrgGetOne(context.Context, *OrgGetOneArgs) (*OrgGetOneReply, error)
	OrgGetAll(context.Context, *commonpb.Empty) (*OrgGetAllReply, error)
	OrgGetOneByDomain(context.Context, *OrgGetByDomainArgs) (*OrgGetOneReply, error)
	OrgGetByEmail(context.Context, *OrgGetByEmailArgs) (*OrgGetOneReply, error)
	OrgGetAllDaysPassedSinceSignup(context.Context, *OrgGetDaysPassedArgs) (*OrgGetAllReply, error)
	OrgGetPrimaryDomain(context.Context, *OrgGetPrimaryDomainArgs) (*OrgGetPrimaryDomainReply, error)
	OrgCreate(context.Context, *OrgMutateArgs) (*OrgGetOneReply, error)
	OrgUpdate(context.Context, *OrgMutateArgs) (*ErrorReply, error)
	OrgDelete(context.Context, *OrgMutateArgs) (*ErrorReply, error)
	OrgAddDomain(context.Context, *OrgAddDomainArgs) (*ErrorReply, error)
	OrgSetPrimaryDomain(context.Context, *OrgSetPrimaryDomainArgs) (*ErrorReply, error)
	OrgCreateSampleData(context.Context, *OrgCreateSampleDataArgs) (*ErrorReply, error)
	// Groups
	GroupGetOne(context.Context, *GroupGetOneArgs) (*GroupGetOneReply, error)
	GroupGetAll(context.Context, *GroupGetAllArgs) (*GroupGetAllReply, error)
	GroupGetByName(context.Context, *GroupGetByNameArgs) (*GroupGetOneReply, error)
	GroupGetMemberUserIDs(context.Context, *GroupGetMemberIDsArgs) (*GroupGetMemberIDsReply, error)
	GroupAddMembers(context.Context, *GroupMembersArgs) (*ErrorReply, error)
	GroupRemoveMembers(context.Context, *GroupMembersArgs) (*ErrorReply, error)
	GroupCreate(context.Context, *GroupMutateArgs) (*ErrorReply, error)
	GroupUpdate(context.Context, *GroupMutateArgs) (*ErrorReply, error)
	GroupDelete(context.Context, *GroupMutateArgs) (*ErrorReply, error)
	// Bookings
	BookingGetOne(context.Context, *BookingGetOneArgs) (*BookingGetOneReply, error)
	// Spaces
	SpaceGetOne(context.Context, *SpaceGetOneArgs) (*SpaceGetOneReply, error)
	SpaceGetCount(context.Context, *SpaceGetCountArgs) (*IntReply, error)
	// Locations
	LocationGetOne(context.Context, *LocationGetOneArgs) (*LocationGetOneReply, error)
	LocationGetCount(context.Context, *LocationGetCountArgs) (*IntReply, error)
	LocationGetTimezone(context.Context, *LocationGetTimezoneArgs) (*StringReply, error)
	// AuthProvider
	AuthProviderCreate(context.Context, *AuthProviderMutateArgs) (*ErrorReply, error)
	AuthProviderUpdate(context.Context, *AuthProviderMutateArgs) (*ErrorReply, error)
	// AuthState
	AuthStateCreate(context.Context, *AuthStateMutateArgs) (*AuthStateGetOneReply, error)
	// General
	SendEmail(context.Context, *SendEmailArgs) (*ErrorReply, error)
	Encrypt(context.Context, *EncryptArgs) (*EncryptReply, error)
	Decrypt(context.Context, *DecryptArgs) (*EncryptReply, error)
	IsValidLanguageCode(context.Context, *IsValidLangArgs) (*BoolReply, error)
	DisablePasswordLogin(context.Context, *commonpb.Empty) (*BoolReply, error)
	FormatPublicURL(context.Context, *FormatPublicURLArgs) (*StringReply, error)
	IsDevelopmentMode(context.Context, *commonpb.Empty) (*BoolReply, error)
	GetPostgresURL(context.Context, *commonpb.Empty) (*StringReply, error)
	mustEmbedUnimplementedHostAPIServiceServer()
}

// UnimplementedHostAPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostAPIServiceServer struct{}

func (UnimplementedHostAPIServiceServer) SettingsGet(context.Context, *SettingsGetArgs) (*SettingsGetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SettingsGet not implemented")
}
func (UnimplementedHostAPIServiceServer) SettingsGetBool(context.Context, *SettingsGetArgs) (*SettingsGetBoolReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SettingsGetBool not implemented")
}
func (UnimplementedHostAPIServiceServer) SettingsGetInt(context.Context, *SettingsGetArgs) (*IntReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SettingsGetInt not implemented")
}
func (UnimplementedHostAPIServiceServer) SettingsGetNullUUID(context.Context, *commonpb.Empty) (*StringReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SettingsGetNullUUID not implemented")
}
func (UnimplementedHostAPIServiceServer) SettingsGetOrgIDsByValue(context.Context, *SettingsGetOrgIDsArgs) (*StringSliceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SettingsGetOrgIDsByValue not implemented")
}
func (UnimplementedHostAPIServiceServer) SettingsSet(context.Context, *SettingsSetArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SettingsSet not implemented")
}
func (UnimplementedHostAPIServiceServer) SettingsDelete(context.Context, *SettingsDeleteArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SettingsDelete not implemented")
}
func (UnimplementedHostAPIServiceServer) UserGetOne(context.Context, *UserGetOneArgs) (*UserGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserGetOne not implemented")
}
func (UnimplementedHostAPIServiceServer) UserGetAll(context.Context, *UserGetAllArgs) (*UserGetAllReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserGetAll not implemented")
}
func (UnimplementedHostAPIServiceServer) UserGetByEmail(context.Context, *UserGetByEmailArgs) (*UserGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserGetByEmail not implemented")
}
func (UnimplementedHostAPIServiceServer) UserGetCount(context.Context, *UserGetCountArgs) (*IntReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserGetCount not implemented")
}
func (UnimplementedHostAPIServiceServer) UserGetHashedPassword(context.Context, *UserHashPasswordArgs) (*StringReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserGetHashedPassword not implemented")
}
func (UnimplementedHostAPIServiceServer) UserGetUsersWithEmail(context.Context, *UserGetUsersWithEmailArgs) (*UserGetUsersWithEmailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserGetUsersWithEmail not implemented")
}
func (UnimplementedHostAPIServiceServer) UserIsOrgAdmin(context.Context, *UserIsAdminArgs) (*BoolReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserIsOrgAdmin not implemented")
}
func (UnimplementedHostAPIServiceServer) UserIsSuperAdmin(context.Context, *UserIsAdminArgs) (*BoolReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserIsSuperAdmin not implemented")
}
func (UnimplementedHostAPIServiceServer) UserCreate(context.Context, *UserMutateArgs) (*UserGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCreate not implemented")
}
func (UnimplementedHostAPIServiceServer) UserUpdate(context.Context, *UserMutateArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserUpdate not implemented")
}
func (UnimplementedHostAPIServiceServer) UserDelete(context.Context, *UserMutateArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UserDelete not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgGetOne(context.Context, *OrgGetOneArgs) (*OrgGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgGetOne not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgGetAll(context.Context, *commonpb.Empty) (*OrgGetAllReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgGetAll not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgGetOneByDomain(context.Context, *OrgGetByDomainArgs) (*OrgGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgGetOneByDomain not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgGetByEmail(context.Context, *OrgGetByEmailArgs) (*OrgGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgGetByEmail not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgGetAllDaysPassedSinceSignup(context.Context, *OrgGetDaysPassedArgs) (*OrgGetAllReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgGetAllDaysPassedSinceSignup not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgGetPrimaryDomain(context.Context, *OrgGetPrimaryDomainArgs) (*OrgGetPrimaryDomainReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgGetPrimaryDomain not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgCreate(context.Context, *OrgMutateArgs) (*OrgGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgCreate not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgUpdate(context.Context, *OrgMutateArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgUpdate not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgDelete(context.Context, *OrgMutateArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgDelete not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgAddDomain(context.Context, *OrgAddDomainArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgAddDomain not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgSetPrimaryDomain(context.Context, *OrgSetPrimaryDomainArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgSetPrimaryDomain not implemented")
}
func (UnimplementedHostAPIServiceServer) OrgCreateSampleData(context.Context, *OrgCreateSampleDataArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OrgCreateSampleData not implemented")
}
func (UnimplementedHostAPIServiceServer) GroupGetOne(context.Context, *GroupGetOneArgs) (*GroupGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupGetOne not implemented")
}
func (UnimplementedHostAPIServiceServer) GroupGetAll(context.Context, *GroupGetAllArgs) (*GroupGetAllReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupGetAll not implemented")
}
func (UnimplementedHostAPIServiceServer) GroupGetByName(context.Context, *GroupGetByNameArgs) (*GroupGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupGetByName not implemented")
}
func (UnimplementedHostAPIServiceServer) GroupGetMemberUserIDs(context.Context, *GroupGetMemberIDsArgs) (*GroupGetMemberIDsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupGetMemberUserIDs not implemented")
}
func (UnimplementedHostAPIServiceServer) GroupAddMembers(context.Context, *GroupMembersArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupAddMembers not implemented")
}
func (UnimplementedHostAPIServiceServer) GroupRemoveMembers(context.Context, *GroupMembersArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupRemoveMembers not implemented")
}
func (UnimplementedHostAPIServiceServer) GroupCreate(context.Context, *GroupMutateArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupCreate not implemented")
}
func (UnimplementedHostAPIServiceServer) GroupUpdate(context.Context, *GroupMutateArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupUpdate not implemented")
}
func (UnimplementedHostAPIServiceServer) GroupDelete(context.Context, *GroupMutateArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupDelete not implemented")
}
func (UnimplementedHostAPIServiceServer) BookingGetOne(context.Context, *BookingGetOneArgs) (*BookingGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BookingGetOne not implemented")
}
func (UnimplementedHostAPIServiceServer) SpaceGetOne(context.Context, *SpaceGetOneArgs) (*SpaceGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SpaceGetOne not implemented")
}
func (UnimplementedHostAPIServiceServer) SpaceGetCount(context.Context, *SpaceGetCountArgs) (*IntReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SpaceGetCount not implemented")
}
func (UnimplementedHostAPIServiceServer) LocationGetOne(context.Context, *LocationGetOneArgs) (*LocationGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LocationGetOne not implemented")
}
func (UnimplementedHostAPIServiceServer) LocationGetCount(context.Context, *LocationGetCountArgs) (*IntReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LocationGetCount not implemented")
}
func (UnimplementedHostAPIServiceServer) LocationGetTimezone(context.Context, *LocationGetTimezoneArgs) (*StringReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LocationGetTimezone not implemented")
}
func (UnimplementedHostAPIServiceServer) AuthProviderCreate(context.Context, *AuthProviderMutateArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthProviderCreate not implemented")
}
func (UnimplementedHostAPIServiceServer) AuthProviderUpdate(context.Context, *AuthProviderMutateArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthProviderUpdate not implemented")
}
func (UnimplementedHostAPIServiceServer) AuthStateCreate(context.Context, *AuthStateMutateArgs) (*AuthStateGetOneReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthStateCreate not implemented")
}
func (UnimplementedHostAPIServiceServer) SendEmail(context.Context, *SendEmailArgs) (*ErrorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedHostAPIServiceServer) Encrypt(context.Context, *EncryptArgs) (*EncryptReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedHostAPIServiceServer) Decrypt(context.Context, *DecryptArgs) (*EncryptReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedHostAPIServiceServer) IsValidLanguageCode(context.Context, *IsValidLangArgs) (*BoolReply, error) {
	return nil, status.Error(codes.Unimplemented, "method IsValidLanguageCode not implemented")
}
func (UnimplementedHostAPIServiceServer) DisablePasswordLogin(context.Context, *commonpb.Empty) (*BoolReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DisablePasswordLogin not implemented")
}
func (UnimplementedHostAPIServiceServer) FormatPublicURL(context.Context, *FormatPublicURLArgs) (*StringReply, error) {
	return nil, status.Error(codes.Unimplemented, "method FormatPublicURL not implemented")
}
func (UnimplementedHostAPIServiceServer) IsDevelopmentMode(context.Context, *commonpb.Empty) (*BoolReply, error) {
	return nil, status.Error(codes.Unimplemented, "method IsDevelopmentMode not implemented")
}
func (UnimplementedHostAPIServiceServer) GetPostgresURL(context.Context, *commonpb.Empty) (*StringReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostgresURL not implemented")
}
func (UnimplementedHostAPIServiceServer) mustEmbedUnimplementedHostAPIServiceServer() {}
func (UnimplementedHostAPIServiceServer) testEmbeddedByValue()                        {}

// UnsafeHostAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostAPIServiceServer will
// result in compilation errors.
type UnsafeHostAPIServiceServer interface {
	mustEmbedUnimplementedHostAPIServiceServer()
}

func RegisterHostAPIServiceServer(s grpc.ServiceRegistrar, srv HostAPIServiceServer) {
	// If the following call panics, it indicates UnimplementedHostAPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostAPIService_ServiceDesc, srv)
}

func _HostAPIService_SettingsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsGetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).SettingsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_SettingsGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).SettingsGet(ctx, req.(*SettingsGetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_SettingsGetBool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsGetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).SettingsGetBool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_SettingsGetBool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).SettingsGetBool(ctx, req.(*SettingsGetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_SettingsGetInt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsGetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).SettingsGetInt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_SettingsGetInt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).SettingsGetInt(ctx, req.(*SettingsGetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_SettingsGetNullUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).SettingsGetNullUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_SettingsGetNullUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).SettingsGetNullUUID(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_SettingsGetOrgIDsByValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsGetOrgIDsArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).SettingsGetOrgIDsByValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_SettingsGetOrgIDsByValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).SettingsGetOrgIDsByValue(ctx, req.(*SettingsGetOrgIDsArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_SettingsSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsSetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).SettingsSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_SettingsSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).SettingsSet(ctx, req.(*SettingsSetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_SettingsDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsDeleteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).SettingsDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_SettingsDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).SettingsDelete(ctx, req.(*SettingsDeleteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserGetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetOneArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserGetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserGetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserGetOne(ctx, req.(*UserGetOneArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetAllArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserGetAll(ctx, req.(*UserGetAllArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserGetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetByEmailArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserGetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserGetByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserGetByEmail(ctx, req.(*UserGetByEmailArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserGetCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetCountArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserGetCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserGetCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserGetCount(ctx, req.(*UserGetCountArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserGetHashedPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserHashPasswordArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserGetHashedPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserGetHashedPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserGetHashedPassword(ctx, req.(*UserHashPasswordArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserGetUsersWithEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetUsersWithEmailArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserGetUsersWithEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserGetUsersWithEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserGetUsersWithEmail(ctx, req.(*UserGetUsersWithEmailArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserIsOrgAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIsAdminArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserIsOrgAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserIsOrgAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserIsOrgAdmin(ctx, req.(*UserIsAdminArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserIsSuperAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIsAdminArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserIsSuperAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserIsSuperAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserIsSuperAdmin(ctx, req.(*UserIsAdminArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserCreate(ctx, req.(*UserMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserUpdate(ctx, req.(*UserMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_UserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).UserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_UserDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).UserDelete(ctx, req.(*UserMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgGetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgGetOneArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgGetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgGetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgGetOne(ctx, req.(*OrgGetOneArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgGetAll(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgGetOneByDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgGetByDomainArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgGetOneByDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgGetOneByDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgGetOneByDomain(ctx, req.(*OrgGetByDomainArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgGetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgGetByEmailArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgGetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgGetByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgGetByEmail(ctx, req.(*OrgGetByEmailArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgGetAllDaysPassedSinceSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgGetDaysPassedArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgGetAllDaysPassedSinceSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgGetAllDaysPassedSinceSignup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgGetAllDaysPassedSinceSignup(ctx, req.(*OrgGetDaysPassedArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgGetPrimaryDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgGetPrimaryDomainArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgGetPrimaryDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgGetPrimaryDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgGetPrimaryDomain(ctx, req.(*OrgGetPrimaryDomainArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgCreate(ctx, req.(*OrgMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgUpdate(ctx, req.(*OrgMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgDelete(ctx, req.(*OrgMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgAddDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgAddDomainArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgAddDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgAddDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgAddDomain(ctx, req.(*OrgAddDomainArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgSetPrimaryDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgSetPrimaryDomainArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgSetPrimaryDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgSetPrimaryDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgSetPrimaryDomain(ctx, req.(*OrgSetPrimaryDomainArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_OrgCreateSampleData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgCreateSampleDataArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).OrgCreateSampleData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_OrgCreateSampleData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).OrgCreateSampleData(ctx, req.(*OrgCreateSampleDataArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_GroupGetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupGetOneArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).GroupGetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_GroupGetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).GroupGetOne(ctx, req.(*GroupGetOneArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_GroupGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupGetAllArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).GroupGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_GroupGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).GroupGetAll(ctx, req.(*GroupGetAllArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_GroupGetByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupGetByNameArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).GroupGetByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_GroupGetByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).GroupGetByName(ctx, req.(*GroupGetByNameArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_GroupGetMemberUserIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupGetMemberIDsArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).GroupGetMemberUserIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_GroupGetMemberUserIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).GroupGetMemberUserIDs(ctx, req.(*GroupGetMemberIDsArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_GroupAddMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMembersArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).GroupAddMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_GroupAddMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).GroupAddMembers(ctx, req.(*GroupMembersArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_GroupRemoveMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMembersArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).GroupRemoveMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_GroupRemoveMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).GroupRemoveMembers(ctx, req.(*GroupMembersArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_GroupCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).GroupCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_GroupCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).GroupCreate(ctx, req.(*GroupMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_GroupUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).GroupUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_GroupUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).GroupUpdate(ctx, req.(*GroupMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_GroupDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).GroupDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_GroupDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).GroupDelete(ctx, req.(*GroupMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_BookingGetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingGetOneArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).BookingGetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_BookingGetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).BookingGetOne(ctx, req.(*BookingGetOneArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_SpaceGetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpaceGetOneArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).SpaceGetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_SpaceGetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).SpaceGetOne(ctx, req.(*SpaceGetOneArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_SpaceGetCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpaceGetCountArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).SpaceGetCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_SpaceGetCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).SpaceGetCount(ctx, req.(*SpaceGetCountArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_LocationGetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationGetOneArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).LocationGetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_LocationGetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).LocationGetOne(ctx, req.(*LocationGetOneArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_LocationGetCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationGetCountArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).LocationGetCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_LocationGetCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).LocationGetCount(ctx, req.(*LocationGetCountArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_LocationGetTimezone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationGetTimezoneArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).LocationGetTimezone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_LocationGetTimezone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).LocationGetTimezone(ctx, req.(*LocationGetTimezoneArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_AuthProviderCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthProviderMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).AuthProviderCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_AuthProviderCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).AuthProviderCreate(ctx, req.(*AuthProviderMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_AuthProviderUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthProviderMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).AuthProviderUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_AuthProviderUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).AuthProviderUpdate(ctx, req.(*AuthProviderMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_AuthStateCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthStateMutateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).AuthStateCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_AuthStateCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).AuthStateCreate(ctx, req.(*AuthStateMutateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).SendEmail(ctx, req.(*SendEmailArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_Encrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).Encrypt(ctx, req.(*EncryptArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_Decrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).Decrypt(ctx, req.(*DecryptArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_IsValidLanguageCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsValidLangArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).IsValidLanguageCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_IsValidLanguageCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).IsValidLanguageCode(ctx, req.(*IsValidLangArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_DisablePasswordLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).DisablePasswordLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_DisablePasswordLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).DisablePasswordLogin(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_FormatPublicURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FormatPublicURLArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).FormatPublicURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_FormatPublicURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).FormatPublicURL(ctx, req.(*FormatPublicURLArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_IsDevelopmentMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).IsDevelopmentMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_IsDevelopmentMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).IsDevelopmentMode(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPIService_GetPostgresURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServiceServer).GetPostgresURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPIService_GetPostgresURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServiceServer).GetPostgresURL(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HostAPIService_ServiceDesc is the grpc.ServiceDesc for HostAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seatsurfing.plugin.v1.HostAPIService",
	HandlerType: (*HostAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SettingsGet",
			Handler:    _HostAPIService_SettingsGet_Handler,
		},
		{
			MethodName: "SettingsGetBool",
			Handler:    _HostAPIService_SettingsGetBool_Handler,
		},
		{
			MethodName: "SettingsGetInt",
			Handler:    _HostAPIService_SettingsGetInt_Handler,
		},
		{
			MethodName: "SettingsGetNullUUID",
			Handler:    _HostAPIService_SettingsGetNullUUID_Handler,
		},
		{
			MethodName: "SettingsGetOrgIDsByValue",
			Handler:    _HostAPIService_SettingsGetOrgIDsByValue_Handler,
		},
		{
			MethodName: "SettingsSet",
			Handler:    _HostAPIService_SettingsSet_Handler,
		},
		{
			MethodName: "SettingsDelete",
			Handler:    _HostAPIService_SettingsDelete_Handler,
		},
		{
			MethodName: "UserGetOne",
			Handler:    _HostAPIService_UserGetOne_Handler,
		},
		{
			MethodName: "UserGetAll",
			Handler:    _HostAPIService_UserGetAll_Handler,
		},
		{
			MethodName: "UserGetByEmail",
			Handler:    _HostAPIService_UserGetByEmail_Handler,
		},
		{
			MethodName: "UserGetCount",
			Handler:    _HostAPIService_UserGetCount_Handler,
		},
		{
			MethodName: "UserGetHashedPassword",
			Handler:    _HostAPIService_UserGetHashedPassword_Handler,
		},
		{
			MethodName: "UserGetUsersWithEmail",
			Handler:    _HostAPIService_UserGetUsersWithEmail_Handler,
		},
		{
			MethodName: "UserIsOrgAdmin",
			Handler:    _HostAPIService_UserIsOrgAdmin_Handler,
		},
		{
			MethodName: "UserIsSuperAdmin",
			Handler:    _HostAPIService_UserIsSuperAdmin_Handler,
		},
		{
			MethodName: "UserCreate",
			Handler:    _HostAPIService_UserCreate_Handler,
		},
		{
			MethodName: "UserUpdate",
			Handler:    _HostAPIService_UserUpdate_Handler,
		},
		{
			MethodName: "UserDelete",
			Handler:    _HostAPIService_UserDelete_Handler,
		},
		{
			MethodName: "OrgGetOne",
			Handler:    _HostAPIService_OrgGetOne_Handler,
		},
		{
			MethodName: "OrgGetAll",
			Handler:    _HostAPIService_OrgGetAll_Handler,
		},
		{
			MethodName: "OrgGetOneByDomain",
			Handler:    _HostAPIService_OrgGetOneByDomain_Handler,
		},
		{
			MethodName: "OrgGetByEmail",
			Handler:    _HostAPIService_OrgGetByEmail_Handler,
		},
		{
			MethodName: "OrgGetAllDaysPassedSinceSignup",
			Handler:    _HostAPIService_OrgGetAllDaysPassedSinceSignup_Handler,
		},
		{
			MethodName: "OrgGetPrimaryDomain",
			Handler:    _HostAPIService_OrgGetPrimaryDomain_Handler,
		},
		{
			MethodName: "OrgCreate",
			Handler:    _HostAPIService_OrgCreate_Handler,
		},
		{
			MethodName: "OrgUpdate",
			Handler:    _HostAPIService_OrgUpdate_Handler,
		},
		{
			MethodName: "OrgDelete",
			Handler:    _HostAPIService_OrgDelete_Handler,
		},
		{
			MethodName: "OrgAddDomain",
			Handler:    _HostAPIService_OrgAddDomain_Handler,
		},
		{
			MethodName: "OrgSetPrimaryDomain",
			Handler:    _HostAPIService_OrgSetPrimaryDomain_Handler,
		},
		{
			MethodName: "OrgCreateSampleData",
			Handler:    _HostAPIService_OrgCreateSampleData_Handler,
		},
		{
			MethodName: "GroupGetOne",
			Handler:    _HostAPIService_GroupGetOne_Handler,
		},
		{
			MethodName: "GroupGetAll",
			Handler:    _HostAPIService_GroupGetAll_Handler,
		},
		{
			MethodName: "GroupGetByName",
			Handler:    _HostAPIService_GroupGetByName_Handler,
		},
		{
			MethodName: "GroupGetMemberUserIDs",
			Handler:    _HostAPIService_GroupGetMemberUserIDs_Handler,
		},
		{
			MethodName: "GroupAddMembers",
			Handler:    _HostAPIService_GroupAddMembers_Handler,
		},
		{
			MethodName: "GroupRemoveMembers",
			Handler:    _HostAPIService_GroupRemoveMembers_Handler,
		},
		{
			MethodName: "GroupCreate",
			Handler:    _HostAPIService_GroupCreate_Handler,
		},
		{
			MethodName: "GroupUpdate",
			Handler:    _HostAPIService_GroupUpdate_Handler,
		},
		{
			MethodName: "GroupDelete",
			Handler:    _HostAPIService_GroupDelete_Handler,
		},
		{
			MethodName: "BookingGetOne",
			Handler:    _HostAPIService_BookingGetOne_Handler,
		},
		{
			MethodName: "SpaceGetOne",
			Handler:    _HostAPIService_SpaceGetOne_Handler,
		},
		{
			MethodName: "SpaceGetCount",
			Handler:    _HostAPIService_SpaceGetCount_Handler,
		},
		{
			MethodName: "LocationGetOne",
			Handler:    _HostAPIService_LocationGetOne_Handler,
		},
		{
			MethodName: "LocationGetCount",
			Handler:    _HostAPIService_LocationGetCount_Handler,
		},
		{
			MethodName: "LocationGetTimezone",
			Handler:    _HostAPIService_LocationGetTimezone_Handler,
		},
		{
			MethodName: "AuthProviderCreate",
			Handler:    _HostAPIService_AuthProviderCreate_Handler,
		},
		{
			MethodName: "AuthProviderUpdate",
			Handler:    _HostAPIService_AuthProviderUpdate_Handler,
		},
		{
			MethodName: "AuthStateCreate",
			Handler:    _HostAPIService_AuthStateCreate_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _HostAPIService_SendEmail_Handler,
		},
		{
			MethodName: "Encrypt",
			Handler:    _HostAPIService_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _HostAPIService_Decrypt_Handler,
		},
		{
			MethodName: "IsValidLanguageCode",
			Handler:    _HostAPIService_IsValidLanguageCode_Handler,
		},
		{
			MethodName: "DisablePasswordLogin",
			Handler:    _HostAPIService_DisablePasswordLogin_Handler,
		},
		{
			MethodName: "FormatPublicURL",
			Handler:    _HostAPIService_FormatPublicURL_Handler,
		},
		{
			MethodName: "IsDevelopmentMode",
			Handler:    _HostAPIService_IsDevelopmentMode_Handler,
		},
		{
			MethodName: "GetPostgresURL",
			Handler:    _HostAPIService_GetPostgresURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hostapi.proto",
}
