// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: common.proto

// Shared entity messages used by both plugin.proto (host -> plugin) and
// hostapi.proto (plugin -> host).
//
// IMPORTANT: field numbers must never be renumbered or reused once released.
// Host and plugin(s) are deployed independently, so wire compatibility across
// versions depends entirely on additive changes (new fields get new numbers).

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId         string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Email                  string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Firstname              string                 `protobuf:"bytes,4,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname               string                 `protobuf:"bytes,5,opt,name=lastname,proto3" json:"lastname,omitempty"`
	AtlassianId            string                 `protobuf:"bytes,6,opt,name=atlassian_id,json=atlassianId,proto3" json:"atlassian_id,omitempty"`
	HashedPassword         string                 `protobuf:"bytes,7,opt,name=hashed_password,json=hashedPassword,proto3" json:"hashed_password,omitempty"`
	AuthProviderId         string                 `protobuf:"bytes,8,opt,name=auth_provider_id,json=authProviderId,proto3" json:"auth_provider_id,omitempty"`
	PasswordPending        bool                   `protobuf:"varint,9,opt,name=password_pending,json=passwordPending,proto3" json:"password_pending,omitempty"`
	PasswordUpdateRequired bool                   `protobuf:"varint,10,opt,name=password_update_required,json=passwordUpdateRequired,proto3" json:"password_update_required,omitempty"`
	Role                   int32                  `protobuf:"varint,11,opt,name=role,proto3" json:"role,omitempty"`
	Disabled               bool                   `protobuf:"varint,12,opt,name=disabled,proto3" json:"disabled,omitempty"`
	BanExpiry              *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=ban_expiry,json=banExpiry,proto3" json:"ban_expiry,omitempty"`
	LastActivityAtUtc      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_activity_at_utc,json=lastActivityAtUtc,proto3" json:"last_activity_at_utc,omitempty"`
	TotpSecret             string                 `protobuf:"bytes,15,opt,name=totp_secret,json=totpSecret,proto3" json:"totp_secret,omitempty"`
	ApiToken               string                 `protobuf:"bytes,16,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *User) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *User) GetAtlassianId() string {
	if x != nil {
		return x.AtlassianId
	}
	return ""
}

func (x *User) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

func (x *User) GetAuthProviderId() string {
	if x != nil {
		return x.AuthProviderId
	}
	return ""
}

func (x *User) GetPasswordPending() bool {
	if x != nil {
		return x.PasswordPending
	}
	return false
}

func (x *User) GetPasswordUpdateRequired() bool {
	if x != nil {
		return x.PasswordUpdateRequired
	}
	return false
}

func (x *User) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *User) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *User) GetBanExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.BanExpiry
	}
	return nil
}

func (x *User) GetLastActivityAtUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivityAtUtc
	}
	return nil
}

func (x *User) GetTotpSecret() string {
	if x != nil {
		return x.TotpSecret
	}
	return ""
}

func (x *User) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

type Organization struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContactFirstname string                 `protobuf:"bytes,3,opt,name=contact_firstname,json=contactFirstname,proto3" json:"contact_firstname,omitempty"`
	ContactLastname  string                 `protobuf:"bytes,4,opt,name=contact_lastname,json=contactLastname,proto3" json:"contact_lastname,omitempty"`
	ContactEmail     string                 `protobuf:"bytes,5,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Language         string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	SignupDate       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=signup_date,json=signupDate,proto3" json:"signup_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetContactFirstname() string {
	if x != nil {
		return x.ContactFirstname
	}
	return ""
}

func (x *Organization) GetContactLastname() string {
	if x != nil {
		return x.ContactLastname
	}
	return ""
}

func (x *Organization) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *Organization) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Organization) GetSignupDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SignupDate
	}
	return nil
}

type Domain struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DomainName     string                 `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Active         bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	VerifyToken    string                 `protobuf:"bytes,4,opt,name=verify_token,json=verifyToken,proto3" json:"verify_token,omitempty"`
	Primary        bool                   `protobuf:"varint,5,opt,name=primary,proto3" json:"primary,omitempty"`
	Accessible     bool                   `protobuf:"varint,6,opt,name=accessible,proto3" json:"accessible,omitempty"`
	AccessCheck    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=access_check,json=accessCheck,proto3" json:"access_check,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Domain) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *Domain) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Domain) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Domain) GetVerifyToken() string {
	if x != nil {
		return x.VerifyToken
	}
	return ""
}

func (x *Domain) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

func (x *Domain) GetAccessible() bool {
	if x != nil {
		return x.Accessible
	}
	return false
}

func (x *Domain) GetAccessCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessCheck
	}
	return nil
}

type Group struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Location struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId        string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name                  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MapWidth              uint32                 `protobuf:"varint,4,opt,name=map_width,json=mapWidth,proto3" json:"map_width,omitempty"`
	MapHeight             uint32                 `protobuf:"varint,5,opt,name=map_height,json=mapHeight,proto3" json:"map_height,omitempty"`
	MapScale              float64                `protobuf:"fixed64,6,opt,name=map_scale,json=mapScale,proto3" json:"map_scale,omitempty"`
	MapMimeType           string                 `protobuf:"bytes,7,opt,name=map_mime_type,json=mapMimeType,proto3" json:"map_mime_type,omitempty"`
	MapType               string                 `protobuf:"bytes,8,opt,name=map_type,json=mapType,proto3" json:"map_type,omitempty"`
	Description           string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	MaxConcurrentBookings uint32                 `protobuf:"varint,10,opt,name=max_concurrent_bookings,json=maxConcurrentBookings,proto3" json:"max_concurrent_bookings,omitempty"`
	Timezone              string                 `protobuf:"bytes,11,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Enabled               bool                   `protobuf:"varint,12,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *Location) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Location) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetMapWidth() uint32 {
	if x != nil {
		return x.MapWidth
	}
	return 0
}

func (x *Location) GetMapHeight() uint32 {
	if x != nil {
		return x.MapHeight
	}
	return 0
}

func (x *Location) GetMapScale() float64 {
	if x != nil {
		return x.MapScale
	}
	return 0
}

func (x *Location) GetMapMimeType() string {
	if x != nil {
		return x.MapMimeType
	}
	return ""
}

func (x *Location) GetMapType() string {
	if x != nil {
		return x.MapType
	}
	return ""
}

func (x *Location) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Location) GetMaxConcurrentBookings() uint32 {
	if x != nil {
		return x.MaxConcurrentBookings
	}
	return 0
}

func (x *Location) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Location) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Space struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocationId     string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	X              uint32                 `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y              uint32                 `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	Width          uint32                 `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height         uint32                 `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Rotation       uint32                 `protobuf:"varint,8,opt,name=rotation,proto3" json:"rotation,omitempty"`
	RequireSubject bool                   `protobuf:"varint,9,opt,name=require_subject,json=requireSubject,proto3" json:"require_subject,omitempty"`
	Enabled        bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	KioskEnabled   bool                   `protobuf:"varint,11,opt,name=kiosk_enabled,json=kioskEnabled,proto3" json:"kiosk_enabled,omitempty"`
	Shape          string                 `protobuf:"bytes,12,opt,name=shape,proto3" json:"shape,omitempty"`
	FontSize       string                 `protobuf:"bytes,13,opt,name=font_size,json=fontSize,proto3" json:"font_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Space) Reset() {
	*x = Space{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *Space) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Space) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Space) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Space) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Space) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Space) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Space) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Space) GetRotation() uint32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Space) GetRequireSubject() bool {
	if x != nil {
		return x.RequireSubject
	}
	return false
}

func (x *Space) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Space) GetKioskEnabled() bool {
	if x != nil {
		return x.KioskEnabled
	}
	return false
}

func (x *Space) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *Space) GetFontSize() string {
	if x != nil {
		return x.FontSize
	}
	return ""
}

type SpaceDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Space         *Space                 `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceDetails) Reset() {
	*x = SpaceDetails{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceDetails) ProtoMessage() {}

func (x *SpaceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceDetails.ProtoReflect.Descriptor instead.
func (*SpaceDetails) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *SpaceDetails) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *SpaceDetails) GetSpace() *Space {
	if x != nil {
		return x.Space
	}
	return nil
}

type Booking struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpaceId               string                 `protobuf:"bytes,3,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Enter                 *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=enter,proto3" json:"enter,omitempty"`
	Leave                 *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=leave,proto3" json:"leave,omitempty"`
	CalDavId              string                 `protobuf:"bytes,6,opt,name=cal_dav_id,json=calDavId,proto3" json:"cal_dav_id,omitempty"`
	Approved              bool                   `protobuf:"varint,7,opt,name=approved,proto3" json:"approved,omitempty"`
	Subject               string                 `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	RecurringId           string                 `protobuf:"bytes,9,opt,name=recurring_id,json=recurringId,proto3" json:"recurring_id,omitempty"`
	CreatedAtUtc          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at_utc,json=createdAtUtc,proto3" json:"created_at_utc,omitempty"`
	LastInfoMailSentAtUtc *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_info_mail_sent_at_utc,json=lastInfoMailSentAtUtc,proto3" json:"last_info_mail_sent_at_utc,omitempty"`
	ReminderSentAtUtc     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=reminder_sent_at_utc,json=reminderSentAtUtc,proto3" json:"reminder_sent_at_utc,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Booking) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *Booking) GetEnter() *timestamppb.Timestamp {
	if x != nil {
		return x.Enter
	}
	return nil
}

func (x *Booking) GetLeave() *timestamppb.Timestamp {
	if x != nil {
		return x.Leave
	}
	return nil
}

func (x *Booking) GetCalDavId() string {
	if x != nil {
		return x.CalDavId
	}
	return ""
}

func (x *Booking) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *Booking) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Booking) GetRecurringId() string {
	if x != nil {
		return x.RecurringId
	}
	return ""
}

func (x *Booking) GetCreatedAtUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtUtc
	}
	return nil
}

func (x *Booking) GetLastInfoMailSentAtUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.LastInfoMailSentAtUtc
	}
	return nil
}

func (x *Booking) GetReminderSentAtUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.ReminderSentAtUtc
	}
	return nil
}

type BookingDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Space         *SpaceDetails          `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserFirstname string                 `protobuf:"bytes,3,opt,name=user_firstname,json=userFirstname,proto3" json:"user_firstname,omitempty"`
	UserLastname  string                 `protobuf:"bytes,4,opt,name=user_lastname,json=userLastname,proto3" json:"user_lastname,omitempty"`
	Booking       *Booking               `protobuf:"bytes,5,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingDetails) Reset() {
	*x = BookingDetails{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingDetails) ProtoMessage() {}

func (x *BookingDetails) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingDetails.ProtoReflect.Descriptor instead.
func (*BookingDetails) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *BookingDetails) GetSpace() *SpaceDetails {
	if x != nil {
		return x.Space
	}
	return nil
}

func (x *BookingDetails) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *BookingDetails) GetUserFirstname() string {
	if x != nil {
		return x.UserFirstname
	}
	return ""
}

func (x *BookingDetails) GetUserLastname() string {
	if x != nil {
		return x.UserLastname
	}
	return ""
}

func (x *BookingDetails) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type AuthProvider struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId         string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name                   string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ProviderType           int32                  `protobuf:"varint,4,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	AuthUrl                string                 `protobuf:"bytes,5,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	TokenUrl               string                 `protobuf:"bytes,6,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	AuthStyle              int32                  `protobuf:"varint,7,opt,name=auth_style,json=authStyle,proto3" json:"auth_style,omitempty"`
	Scopes                 string                 `protobuf:"bytes,8,opt,name=scopes,proto3" json:"scopes,omitempty"`
	UserInfoUrl            string                 `protobuf:"bytes,9,opt,name=user_info_url,json=userInfoUrl,proto3" json:"user_info_url,omitempty"`
	UserInfoEmailField     string                 `protobuf:"bytes,10,opt,name=user_info_email_field,json=userInfoEmailField,proto3" json:"user_info_email_field,omitempty"`
	UserInfoFirstnameField string                 `protobuf:"bytes,11,opt,name=user_info_firstname_field,json=userInfoFirstnameField,proto3" json:"user_info_firstname_field,omitempty"`
	UserInfoLastnameField  string                 `protobuf:"bytes,12,opt,name=user_info_lastname_field,json=userInfoLastnameField,proto3" json:"user_info_lastname_field,omitempty"`
	ClientId               string                 `protobuf:"bytes,13,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret           string                 `protobuf:"bytes,14,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	LogoutUrl              string                 `protobuf:"bytes,15,opt,name=logout_url,json=logoutUrl,proto3" json:"logout_url,omitempty"`
	ProfilePageUrl         string                 `protobuf:"bytes,16,opt,name=profile_page_url,json=profilePageUrl,proto3" json:"profile_page_url,omitempty"`
	ReadOnly               bool                   `protobuf:"varint,17,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthProvider) Reset() {
	*x = AuthProvider{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProvider) ProtoMessage() {}

func (x *AuthProvider) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProvider.ProtoReflect.Descriptor instead.
func (*AuthProvider) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *AuthProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthProvider) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AuthProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthProvider) GetProviderType() int32 {
	if x != nil {
		return x.ProviderType
	}
	return 0
}

func (x *AuthProvider) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *AuthProvider) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *AuthProvider) GetAuthStyle() int32 {
	if x != nil {
		return x.AuthStyle
	}
	return 0
}

func (x *AuthProvider) GetScopes() string {
	if x != nil {
		return x.Scopes
	}
	return ""
}

func (x *AuthProvider) GetUserInfoUrl() string {
	if x != nil {
		return x.UserInfoUrl
	}
	return ""
}

func (x *AuthProvider) GetUserInfoEmailField() string {
	if x != nil {
		return x.UserInfoEmailField
	}
	return ""
}

func (x *AuthProvider) GetUserInfoFirstnameField() string {
	if x != nil {
		return x.UserInfoFirstnameField
	}
	return ""
}

func (x *AuthProvider) GetUserInfoLastnameField() string {
	if x != nil {
		return x.UserInfoLastnameField
	}
	return ""
}

func (x *AuthProvider) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthProvider) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *AuthProvider) GetLogoutUrl() string {
	if x != nil {
		return x.LogoutUrl
	}
	return ""
}

func (x *AuthProvider) GetProfilePageUrl() string {
	if x != nil {
		return x.ProfilePageUrl
	}
	return ""
}

func (x *AuthProvider) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type AuthState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthProviderId string                 `protobuf:"bytes,2,opt,name=auth_provider_id,json=authProviderId,proto3" json:"auth_provider_id,omitempty"`
	Expiry         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	AuthStateType  int32                  `protobuf:"varint,4,opt,name=auth_state_type,json=authStateType,proto3" json:"auth_state_type,omitempty"`
	Payload        string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthState) Reset() {
	*x = AuthState{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthState) ProtoMessage() {}

func (x *AuthState) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthState.ProtoReflect.Descriptor instead.
func (*AuthState) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *AuthState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthState) GetAuthProviderId() string {
	if x != nil {
		return x.AuthProviderId
	}
	return ""
}

func (x *AuthState) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *AuthState) GetAuthStateType() int32 {
	if x != nil {
		return x.AuthStateType
	}
	return 0
}

func (x *AuthState) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x15seatsurfing.plugin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xe0\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1c\n" +
	"\tfirstname\x18\x04 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x05 \x01(\tR\blastname\x12!\n" +
	"\fatlassian_id\x18\x06 \x01(\tR\vatlassianId\x12'\n" +
	"\x0fhashed_password\x18\a \x01(\tR\x0ehashedPassword\x12(\n" +
	"\x10auth_provider_id\x18\b \x01(\tR\x0eauthProviderId\x12)\n" +
	"\x10password_pending\x18\t \x01(\bR\x0fpasswordPending\x128\n" +
	"\x18password_update_required\x18\n" +
	" \x01(\bR\x16passwordUpdateRequired\x12\x12\n" +
	"\x04role\x18\v \x01(\x05R\x04role\x12\x1a\n" +
	"\bdisabled\x18\f \x01(\bR\bdisabled\x129\n" +
	"\n" +
	"ban_expiry\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tbanExpiry\x12K\n" +
	"\x14last_activity_at_utc\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x11lastActivityAtUtc\x12\x1f\n" +
	"\vtotp_secret\x18\x0f \x01(\tR\n" +
	"totpSecret\x12\x1b\n" +
	"\tapi_token\x18\x10 \x01(\tR\bapiToken\"\x88\x02\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x11contact_firstname\x18\x03 \x01(\tR\x10contactFirstname\x12)\n" +
	"\x10contact_lastname\x18\x04 \x01(\tR\x0fcontactLastname\x12#\n" +
	"\rcontact_email\x18\x05 \x01(\tR\fcontactEmail\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12;\n" +
	"\vsignup_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"signupDate\"\x86\x02\n" +
	"\x06Domain\x12\x1f\n" +
	"\vdomain_name\x18\x01 \x01(\tR\n" +
	"domainName\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12!\n" +
	"\fverify_token\x18\x04 \x01(\tR\vverifyToken\x12\x18\n" +
	"\aprimary\x18\x05 \x01(\bR\aprimary\x12\x1e\n" +
	"\n" +
	"accessible\x18\x06 \x01(\bR\n" +
	"accessible\x12=\n" +
	"\faccess_check\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vaccessCheck\"T\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xff\x02\n" +
	"\bLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tmap_width\x18\x04 \x01(\rR\bmapWidth\x12\x1d\n" +
	"\n" +
	"map_height\x18\x05 \x01(\rR\tmapHeight\x12\x1b\n" +
	"\tmap_scale\x18\x06 \x01(\x01R\bmapScale\x12\"\n" +
	"\rmap_mime_type\x18\a \x01(\tR\vmapMimeType\x12\x19\n" +
	"\bmap_type\x18\b \x01(\tR\amapType\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x126\n" +
	"\x17max_concurrent_bookings\x18\n" +
	" \x01(\rR\x15maxConcurrentBookings\x12\x1a\n" +
	"\btimezone\x18\v \x01(\tR\btimezone\x12\x18\n" +
	"\aenabled\x18\f \x01(\bR\aenabled\"\xcd\x02\n" +
	"\x05Space\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x04 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\rR\x01y\x12\x14\n" +
	"\x05width\x18\x06 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\rR\x06height\x12\x1a\n" +
	"\brotation\x18\b \x01(\rR\brotation\x12'\n" +
	"\x0frequire_subject\x18\t \x01(\bR\x0erequireSubject\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12#\n" +
	"\rkiosk_enabled\x18\v \x01(\bR\fkioskEnabled\x12\x14\n" +
	"\x05shape\x18\f \x01(\tR\x05shape\x12\x1b\n" +
	"\tfont_size\x18\r \x01(\tR\bfontSize\"\x7f\n" +
	"\fSpaceDetails\x12;\n" +
	"\blocation\x18\x01 \x01(\v2\x1f.seatsurfing.plugin.v1.LocationR\blocation\x122\n" +
	"\x05space\x18\x02 \x01(\v2\x1c.seatsurfing.plugin.v1.SpaceR\x05space\"\x8e\x04\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bspace_id\x18\x03 \x01(\tR\aspaceId\x120\n" +
	"\x05enter\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05enter\x120\n" +
	"\x05leave\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05leave\x12\x1c\n" +
	"\n" +
	"cal_dav_id\x18\x06 \x01(\tR\bcalDavId\x12\x1a\n" +
	"\bapproved\x18\a \x01(\bR\bapproved\x12\x18\n" +
	"\asubject\x18\b \x01(\tR\asubject\x12!\n" +
	"\frecurring_id\x18\t \x01(\tR\vrecurringId\x12@\n" +
	"\x0ecreated_at_utc\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAtUtc\x12U\n" +
	"\x1alast_info_mail_sent_at_utc\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x15lastInfoMailSentAtUtc\x12K\n" +
	"\x14reminder_sent_at_utc\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x11reminderSentAtUtc\"\xf0\x01\n" +
	"\x0eBookingDetails\x129\n" +
	"\x05space\x18\x01 \x01(\v2#.seatsurfing.plugin.v1.SpaceDetailsR\x05space\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12%\n" +
	"\x0euser_firstname\x18\x03 \x01(\tR\ruserFirstname\x12#\n" +
	"\ruser_lastname\x18\x04 \x01(\tR\fuserLastname\x128\n" +
	"\abooking\x18\x05 \x01(\v2\x1e.seatsurfing.plugin.v1.BookingR\abooking\"\xe2\x04\n" +
	"\fAuthProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rprovider_type\x18\x04 \x01(\x05R\fproviderType\x12\x19\n" +
	"\bauth_url\x18\x05 \x01(\tR\aauthUrl\x12\x1b\n" +
	"\ttoken_url\x18\x06 \x01(\tR\btokenUrl\x12\x1d\n" +
	"\n" +
	"auth_style\x18\a \x01(\x05R\tauthStyle\x12\x16\n" +
	"\x06scopes\x18\b \x01(\tR\x06scopes\x12\"\n" +
	"\ruser_info_url\x18\t \x01(\tR\vuserInfoUrl\x121\n" +
	"\x15user_info_email_field\x18\n" +
	" \x01(\tR\x12userInfoEmailField\x129\n" +
	"\x19user_info_firstname_field\x18\v \x01(\tR\x16userInfoFirstnameField\x127\n" +
	"\x18user_info_lastname_field\x18\f \x01(\tR\x15userInfoLastnameField\x12\x1b\n" +
	"\tclient_id\x18\r \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x0e \x01(\tR\fclientSecret\x12\x1d\n" +
	"\n" +
	"logout_url\x18\x0f \x01(\tR\tlogoutUrl\x12(\n" +
	"\x10profile_page_url\x18\x10 \x01(\tR\x0eprofilePageUrl\x12\x1b\n" +
	"\tread_only\x18\x11 \x01(\bR\breadOnly\"\xbb\x01\n" +
	"\tAuthState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10auth_provider_id\x18\x02 \x01(\tR\x0eauthProviderId\x122\n" +
	"\x06expiry\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12&\n" +
	"\x0fauth_state_type\x18\x04 \x01(\x05R\rauthStateType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayloadB8Z6github.com/seatsurfing/seatsurfing/server/api/commonpbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_common_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: seatsurfing.plugin.v1.Empty
	(*User)(nil),                  // 1: seatsurfing.plugin.v1.User
	(*Organization)(nil),          // 2: seatsurfing.plugin.v1.Organization
	(*Domain)(nil),                // 3: seatsurfing.plugin.v1.Domain
	(*Group)(nil),                 // 4: seatsurfing.plugin.v1.Group
	(*Location)(nil),              // 5: seatsurfing.plugin.v1.Location
	(*Space)(nil),                 // 6: seatsurfing.plugin.v1.Space
	(*SpaceDetails)(nil),          // 7: seatsurfing.plugin.v1.SpaceDetails
	(*Booking)(nil),               // 8: seatsurfing.plugin.v1.Booking
	(*BookingDetails)(nil),        // 9: seatsurfing.plugin.v1.BookingDetails
	(*AuthProvider)(nil),          // 10: seatsurfing.plugin.v1.AuthProvider
	(*AuthState)(nil),             // 11: seatsurfing.plugin.v1.AuthState
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	12, // 0: seatsurfing.plugin.v1.User.ban_expiry:type_name -> google.protobuf.Timestamp
	12, // 1: seatsurfing.plugin.v1.User.last_activity_at_utc:type_name -> google.protobuf.Timestamp
	12, // 2: seatsurfing.plugin.v1.Organization.signup_date:type_name -> google.protobuf.Timestamp
	12, // 3: seatsurfing.plugin.v1.Domain.access_check:type_name -> google.protobuf.Timestamp
	5,  // 4: seatsurfing.plugin.v1.SpaceDetails.location:type_name -> seatsurfing.plugin.v1.Location
	6,  // 5: seatsurfing.plugin.v1.SpaceDetails.space:type_name -> seatsurfing.plugin.v1.Space
	12, // 6: seatsurfing.plugin.v1.Booking.enter:type_name -> google.protobuf.Timestamp
	12, // 7: seatsurfing.plugin.v1.Booking.leave:type_name -> google.protobuf.Timestamp
	12, // 8: seatsurfing.plugin.v1.Booking.created_at_utc:type_name -> google.protobuf.Timestamp
	12, // 9: seatsurfing.plugin.v1.Booking.last_info_mail_sent_at_utc:type_name -> google.protobuf.Timestamp
	12, // 10: seatsurfing.plugin.v1.Booking.reminder_sent_at_utc:type_name -> google.protobuf.Timestamp
	7,  // 11: seatsurfing.plugin.v1.BookingDetails.space:type_name -> seatsurfing.plugin.v1.SpaceDetails
	8,  // 12: seatsurfing.plugin.v1.BookingDetails.booking:type_name -> seatsurfing.plugin.v1.Booking
	12, // 13: seatsurfing.plugin.v1.AuthState.expiry:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
