// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: plugin.proto

// Host -> plugin RPCs: mirrors the api.SeatsurfingPlugin interface.
//
// IMPORTANT: field numbers must never be renumbered or reused once released.
// Host and plugin(s) are deployed independently, so wire compatibility across
// versions depends entirely on additive changes (new fields get new numbers).

package pluginpb

import (
	commonpb "github.com/seatsurfing/seatsurfing/server/api/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *IdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StringListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringListReply) Reset() {
	*x = StringListReply{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringListReply) ProtoMessage() {}

func (x *StringListReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringListReply.ProtoReflect.Descriptor instead.
func (*StringListReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *StringListReply) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type BasePathReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasePathReply) Reset() {
	*x = BasePathReply{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasePathReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasePathReply) ProtoMessage() {}

func (x *BasePathReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasePathReply.ProtoReflect.Descriptor instead.
func (*BasePathReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *BasePathReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AdminUIMenuItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// source is the URL of the plugin's UI entry point. If tag_name is empty,
	// it is an HTML page rendered in an iframe (legacy); if tag_name is set,
	// it is a JS module that registers the given custom element tag.
	Source     string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Visibility string `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Icon       string `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	// tag_name is the custom element tag to mount for this menu item's UI
	// once the JS module at source has been loaded. Empty means the host
	// falls back to the legacy iframe embedding of source.
	TagName       string `protobuf:"bytes,6,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUIMenuItem) Reset() {
	*x = AdminUIMenuItem{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUIMenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUIMenuItem) ProtoMessage() {}

func (x *AdminUIMenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUIMenuItem.ProtoReflect.Descriptor instead.
func (*AdminUIMenuItem) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminUIMenuItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminUIMenuItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminUIMenuItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AdminUIMenuItem) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *AdminUIMenuItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AdminUIMenuItem) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

type AdminUIMenuItemsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AdminUIMenuItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUIMenuItemsReply) Reset() {
	*x = AdminUIMenuItemsReply{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUIMenuItemsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUIMenuItemsReply) ProtoMessage() {}

func (x *AdminUIMenuItemsReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUIMenuItemsReply.ProtoReflect.Descriptor instead.
func (*AdminUIMenuItemsReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminUIMenuItemsReply) GetItems() []*AdminUIMenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AdminWelcomeScreen struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source is the URL of the plugin's welcome screen UI. See AdminUIMenuItem
	// for the meaning of source/tag_name depending on whether tag_name is set.
	Source            string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	SkipOnSettingTrue string `protobuf:"bytes,2,opt,name=skip_on_setting_true,json=skipOnSettingTrue,proto3" json:"skip_on_setting_true,omitempty"`
	TagName           string `protobuf:"bytes,3,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminWelcomeScreen) Reset() {
	*x = AdminWelcomeScreen{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminWelcomeScreen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminWelcomeScreen) ProtoMessage() {}

func (x *AdminWelcomeScreen) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminWelcomeScreen.ProtoReflect.Descriptor instead.
func (*AdminWelcomeScreen) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *AdminWelcomeScreen) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AdminWelcomeScreen) GetSkipOnSettingTrue() string {
	if x != nil {
		return x.SkipOnSettingTrue
	}
	return ""
}

func (x *AdminWelcomeScreen) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

type AdminWelcomeScreenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       bool                   `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	Screen        *AdminWelcomeScreen    `protobuf:"bytes,2,opt,name=screen,proto3" json:"screen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminWelcomeScreenReply) Reset() {
	*x = AdminWelcomeScreenReply{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminWelcomeScreenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminWelcomeScreenReply) ProtoMessage() {}

func (x *AdminWelcomeScreenReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminWelcomeScreenReply.ProtoReflect.Descriptor instead.
func (*AdminWelcomeScreenReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminWelcomeScreenReply) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *AdminWelcomeScreenReply) GetScreen() *AdminWelcomeScreen {
	if x != nil {
		return x.Screen
	}
	return nil
}

type GetPublicSettingsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPublicSettingsRequest) Reset() {
	*x = GetPublicSettingsRequest{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicSettingsRequest) ProtoMessage() {}

func (x *GetPublicSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetPublicSettingsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *GetPublicSettingsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type PluginSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	SettingType   int32                  `protobuf:"varint,3,opt,name=setting_type,json=settingType,proto3" json:"setting_type,omitempty"` // maps api.SettingType int constants
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginSetting) Reset() {
	*x = PluginSetting{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSetting) ProtoMessage() {}

func (x *PluginSetting) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSetting.ProtoReflect.Descriptor instead.
func (*PluginSetting) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PluginSetting) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PluginSetting) GetSettingType() int32 {
	if x != nil {
		return x.SettingType
	}
	return 0
}

type PluginSettingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*PluginSetting       `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginSettingsReply) Reset() {
	*x = PluginSettingsReply{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSettingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSettingsReply) ProtoMessage() {}

func (x *PluginSettingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSettingsReply.ProtoReflect.Descriptor instead.
func (*PluginSettingsReply) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PluginSettingsReply) GetSettings() []*PluginSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type HttpRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Method        string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	RawQuery      string                   `protobuf:"bytes,3,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	UserId        string                   `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type HttpResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StatusCode    int32                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]*HeaderValues `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x15seatsurfing.plugin.v1\x1a\fcommon.proto\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x0fStringListReply\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"%\n" +
	"\rBasePathReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x9e\x01\n" +
	"\x0fAdminUIMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x19\n" +
	"\btag_name\x18\x06 \x01(\tR\atagName\"U\n" +
	"\x15AdminUIMenuItemsReply\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.seatsurfing.plugin.v1.AdminUIMenuItemR\x05items\"x\n" +
	"\x12AdminWelcomeScreen\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12/\n" +
	"\x14skip_on_setting_true\x18\x02 \x01(\tR\x11skipOnSettingTrue\x12\x19\n" +
	"\btag_name\x18\x03 \x01(\tR\atagName\"v\n" +
	"\x17AdminWelcomeScreenReply\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12A\n" +
	"\x06screen\x18\x02 \x01(\v2).seatsurfing.plugin.v1.AdminWelcomeScreenR\x06screen\"C\n" +
	"\x18GetPublicSettingsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"\\\n" +
	"\rPluginSetting\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12!\n" +
	"\fsetting_type\x18\x03 \x01(\x05R\vsettingType\"W\n" +
	"\x13PluginSettingsReply\x12@\n" +
	"\bsettings\x18\x01 \x03(\v2$.seatsurfing.plugin.v1.PluginSettingR\bsettings\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xaf\x02\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1b\n" +
	"\traw_query\x18\x03 \x01(\tR\brawQuery\x12I\n" +
	"\aheaders\x18\x04 \x03(\v2/.seatsurfing.plugin.v1.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x1a_\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.seatsurfing.plugin.v1.HeaderValuesR\x05value:\x028\x01\"\xf0\x01\n" +
	"\fHttpResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12J\n" +
	"\aheaders\x18\x02 \x03(\v20.seatsurfing.plugin.v1.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a_\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.seatsurfing.plugin.v1.HeaderValuesR\x05value:\x028\x012\x9f\r\n" +
	"\x18SeatsurfingPluginService\x12Q\n" +
	"\vGetBasePath\x12\x1c.seatsurfing.plugin.v1.Empty\x1a$.seatsurfing.plugin.v1.BasePathReply\x12V\n" +
	"\x0eGetRoutePrefix\x12\x1c.seatsurfing.plugin.v1.Empty\x1a&.seatsurfing.plugin.v1.StringListReply\x12]\n" +
	"\x15GetUnauthorizedRoutes\x12\x1c.seatsurfing.plugin.v1.Empty\x1a&.seatsurfing.plugin.v1.StringListReply\x12N\n" +
	"\x10RunSchemaUpdates\x12\x1c.seatsurfing.plugin.v1.Empty\x1a\x1c.seatsurfing.plugin.v1.Empty\x12a\n" +
	"\x13GetAdminUIMenuItems\x12\x1c.seatsurfing.plugin.v1.Empty\x1a,.seatsurfing.plugin.v1.AdminUIMenuItemsReply\x12E\n" +
	"\aOnTimer\x12\x1c.seatsurfing.plugin.v1.Empty\x1a\x1c.seatsurfing.plugin.v1.Empty\x12D\n" +
	"\x06OnInit\x12\x1c.seatsurfing.plugin.v1.Empty\x1a\x1c.seatsurfing.plugin.v1.Empty\x12e\n" +
	"\x15GetAdminWelcomeScreen\x12\x1c.seatsurfing.plugin.v1.Empty\x1a..seatsurfing.plugin.v1.AdminWelcomeScreenReply\x12p\n" +
	"\x11GetPublicSettings\x12/.seatsurfing.plugin.v1.GetPublicSettingsRequest\x1a*.seatsurfing.plugin.v1.PluginSettingsReply\x12\\\n" +
	"\x11HandleHTTPRequest\x12\".seatsurfing.plugin.v1.HttpRequest\x1a#.seatsurfing.plugin.v1.HttpResponse\x12O\n" +
	"\rOnUserCreated\x12 .seatsurfing.plugin.v1.IdRequest\x1a\x1c.seatsurfing.plugin.v1.Empty\x12O\n" +
	"\rOnUserUpdated\x12 .seatsurfing.plugin.v1.IdRequest\x1a\x1c.seatsurfing.plugin.v1.Empty\x12T\n" +
	"\x12OnBeforeUserDelete\x12 .seatsurfing.plugin.v1.IdRequest\x1a\x1c.seatsurfing.plugin.v1.Empty\x12W\n" +
	"\x15OnOrganizationCreated\x12 .seatsurfing.plugin.v1.IdRequest\x1a\x1c.seatsurfing.plugin.v1.Empty\x12W\n" +
	"\x15OnOrganizationUpdated\x12 .seatsurfing.plugin.v1.IdRequest\x1a\x1c.seatsurfing.plugin.v1.Empty\x12\\\n" +
	"\x1aOnBeforeOrganizationDelete\x12 .seatsurfing.plugin.v1.IdRequest\x1a\x1c.seatsurfing.plugin.v1.Empty\x12R\n" +
	"\x10OnBookingCreated\x12 .seatsurfing.plugin.v1.IdRequest\x1a\x1c.seatsurfing.plugin.v1.Empty\x12R\n" +
	"\x10OnBookingUpdated\x12 .seatsurfing.plugin.v1.IdRequest\x1a\x1c.seatsurfing.plugin.v1.Empty\x12R\n" +
	"\x10OnBookingDeleted\x12 .seatsurfing.plugin.v1.IdRequest\x1a\x1c.seatsurfing.plugin.v1.EmptyB8Z6github.com/seatsurfing/seatsurfing/server/api/pluginpbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_plugin_proto_goTypes = []any{
	(*IdRequest)(nil),                // 0: seatsurfing.plugin.v1.IdRequest
	(*StringListReply)(nil),          // 1: seatsurfing.plugin.v1.StringListReply
	(*BasePathReply)(nil),            // 2: seatsurfing.plugin.v1.BasePathReply
	(*AdminUIMenuItem)(nil),          // 3: seatsurfing.plugin.v1.AdminUIMenuItem
	(*AdminUIMenuItemsReply)(nil),    // 4: seatsurfing.plugin.v1.AdminUIMenuItemsReply
	(*AdminWelcomeScreen)(nil),       // 5: seatsurfing.plugin.v1.AdminWelcomeScreen
	(*AdminWelcomeScreenReply)(nil),  // 6: seatsurfing.plugin.v1.AdminWelcomeScreenReply
	(*GetPublicSettingsRequest)(nil), // 7: seatsurfing.plugin.v1.GetPublicSettingsRequest
	(*PluginSetting)(nil),            // 8: seatsurfing.plugin.v1.PluginSetting
	(*PluginSettingsReply)(nil),      // 9: seatsurfing.plugin.v1.PluginSettingsReply
	(*HeaderValues)(nil),             // 10: seatsurfing.plugin.v1.HeaderValues
	(*HttpRequest)(nil),              // 11: seatsurfing.plugin.v1.HttpRequest
	(*HttpResponse)(nil),             // 12: seatsurfing.plugin.v1.HttpResponse
	nil,                              // 13: seatsurfing.plugin.v1.HttpRequest.HeadersEntry
	nil,                              // 14: seatsurfing.plugin.v1.HttpResponse.HeadersEntry
	(*commonpb.Empty)(nil),           // 15: seatsurfing.plugin.v1.Empty
}
var file_plugin_proto_depIdxs = []int32{
	3,  // 0: seatsurfing.plugin.v1.AdminUIMenuItemsReply.items:type_name -> seatsurfing.plugin.v1.AdminUIMenuItem
	5,  // 1: seatsurfing.plugin.v1.AdminWelcomeScreenReply.screen:type_name -> seatsurfing.plugin.v1.AdminWelcomeScreen
	8,  // 2: seatsurfing.plugin.v1.PluginSettingsReply.settings:type_name -> seatsurfing.plugin.v1.PluginSetting
	13, // 3: seatsurfing.plugin.v1.HttpRequest.headers:type_name -> seatsurfing.plugin.v1.HttpRequest.HeadersEntry
	14, // 4: seatsurfing.plugin.v1.HttpResponse.headers:type_name -> seatsurfing.plugin.v1.HttpResponse.HeadersEntry
	10, // 5: seatsurfing.plugin.v1.HttpRequest.HeadersEntry.value:type_name -> seatsurfing.plugin.v1.HeaderValues
	10, // 6: seatsurfing.plugin.v1.HttpResponse.HeadersEntry.value:type_name -> seatsurfing.plugin.v1.HeaderValues
	15, // 7: seatsurfing.plugin.v1.SeatsurfingPluginService.GetBasePath:input_type -> seatsurfing.plugin.v1.Empty
	15, // 8: seatsurfing.plugin.v1.SeatsurfingPluginService.GetRoutePrefix:input_type -> seatsurfing.plugin.v1.Empty
	15, // 9: seatsurfing.plugin.v1.SeatsurfingPluginService.GetUnauthorizedRoutes:input_type -> seatsurfing.plugin.v1.Empty
	15, // 10: seatsurfing.plugin.v1.SeatsurfingPluginService.RunSchemaUpdates:input_type -> seatsurfing.plugin.v1.Empty
	15, // 11: seatsurfing.plugin.v1.SeatsurfingPluginService.GetAdminUIMenuItems:input_type -> seatsurfing.plugin.v1.Empty
	15, // 12: seatsurfing.plugin.v1.SeatsurfingPluginService.OnTimer:input_type -> seatsurfing.plugin.v1.Empty
	15, // 13: seatsurfing.plugin.v1.SeatsurfingPluginService.OnInit:input_type -> seatsurfing.plugin.v1.Empty
	15, // 14: seatsurfing.plugin.v1.SeatsurfingPluginService.GetAdminWelcomeScreen:input_type -> seatsurfing.plugin.v1.Empty
	7,  // 15: seatsurfing.plugin.v1.SeatsurfingPluginService.GetPublicSettings:input_type -> seatsurfing.plugin.v1.GetPublicSettingsRequest
	11, // 16: seatsurfing.plugin.v1.SeatsurfingPluginService.HandleHTTPRequest:input_type -> seatsurfing.plugin.v1.HttpRequest
	0,  // 17: seatsurfing.plugin.v1.SeatsurfingPluginService.OnUserCreated:input_type -> seatsurfing.plugin.v1.IdRequest
	0,  // 18: seatsurfing.plugin.v1.SeatsurfingPluginService.OnUserUpdated:input_type -> seatsurfing.plugin.v1.IdRequest
	0,  // 19: seatsurfing.plugin.v1.SeatsurfingPluginService.OnBeforeUserDelete:input_type -> seatsurfing.plugin.v1.IdRequest
	0,  // 20: seatsurfing.plugin.v1.SeatsurfingPluginService.OnOrganizationCreated:input_type -> seatsurfing.plugin.v1.IdRequest
	0,  // 21: seatsurfing.plugin.v1.SeatsurfingPluginService.OnOrganizationUpdated:input_type -> seatsurfing.plugin.v1.IdRequest
	0,  // 22: seatsurfing.plugin.v1.SeatsurfingPluginService.OnBeforeOrganizationDelete:input_type -> seatsurfing.plugin.v1.IdRequest
	0,  // 23: seatsurfing.plugin.v1.SeatsurfingPluginService.OnBookingCreated:input_type -> seatsurfing.plugin.v1.IdRequest
	0,  // 24: seatsurfing.plugin.v1.SeatsurfingPluginService.OnBookingUpdated:input_type -> seatsurfing.plugin.v1.IdRequest
	0,  // 25: seatsurfing.plugin.v1.SeatsurfingPluginService.OnBookingDeleted:input_type -> seatsurfing.plugin.v1.IdRequest
	2,  // 26: seatsurfing.plugin.v1.SeatsurfingPluginService.GetBasePath:output_type -> seatsurfing.plugin.v1.BasePathReply
	1,  // 27: seatsurfing.plugin.v1.SeatsurfingPluginService.GetRoutePrefix:output_type -> seatsurfing.plugin.v1.StringListReply
	1,  // 28: seatsurfing.plugin.v1.SeatsurfingPluginService.GetUnauthorizedRoutes:output_type -> seatsurfing.plugin.v1.StringListReply
	15, // 29: seatsurfing.plugin.v1.SeatsurfingPluginService.RunSchemaUpdates:output_type -> seatsurfing.plugin.v1.Empty
	4,  // 30: seatsurfing.plugin.v1.SeatsurfingPluginService.GetAdminUIMenuItems:output_type -> seatsurfing.plugin.v1.AdminUIMenuItemsReply
	15, // 31: seatsurfing.plugin.v1.SeatsurfingPluginService.OnTimer:output_type -> seatsurfing.plugin.v1.Empty
	15, // 32: seatsurfing.plugin.v1.SeatsurfingPluginService.OnInit:output_type -> seatsurfing.plugin.v1.Empty
	6,  // 33: seatsurfing.plugin.v1.SeatsurfingPluginService.GetAdminWelcomeScreen:output_type -> seatsurfing.plugin.v1.AdminWelcomeScreenReply
	9,  // 34: seatsurfing.plugin.v1.SeatsurfingPluginService.GetPublicSettings:output_type -> seatsurfing.plugin.v1.PluginSettingsReply
	12, // 35: seatsurfing.plugin.v1.SeatsurfingPluginService.HandleHTTPRequest:output_type -> seatsurfing.plugin.v1.HttpResponse
	15, // 36: seatsurfing.plugin.v1.SeatsurfingPluginService.OnUserCreated:output_type -> seatsurfing.plugin.v1.Empty
	15, // 37: seatsurfing.plugin.v1.SeatsurfingPluginService.OnUserUpdated:output_type -> seatsurfing.plugin.v1.Empty
	15, // 38: seatsurfing.plugin.v1.SeatsurfingPluginService.OnBeforeUserDelete:output_type -> seatsurfing.plugin.v1.Empty
	15, // 39: seatsurfing.plugin.v1.SeatsurfingPluginService.OnOrganizationCreated:output_type -> seatsurfing.plugin.v1.Empty
	15, // 40: seatsurfing.plugin.v1.SeatsurfingPluginService.OnOrganizationUpdated:output_type -> seatsurfing.plugin.v1.Empty
	15, // 41: seatsurfing.plugin.v1.SeatsurfingPluginService.OnBeforeOrganizationDelete:output_type -> seatsurfing.plugin.v1.Empty
	15, // 42: seatsurfing.plugin.v1.SeatsurfingPluginService.OnBookingCreated:output_type -> seatsurfing.plugin.v1.Empty
	15, // 43: seatsurfing.plugin.v1.SeatsurfingPluginService.OnBookingUpdated:output_type -> seatsurfing.plugin.v1.Empty
	15, // 44: seatsurfing.plugin.v1.SeatsurfingPluginService.OnBookingDeleted:output_type -> seatsurfing.plugin.v1.Empty
	26, // [26:45] is the sub-list for method output_type
	7,  // [7:26] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
