// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: plugin.proto

// Host -> plugin RPCs: mirrors the api.SeatsurfingPlugin interface.
//
// IMPORTANT: field numbers must never be renumbered or reused once released.
// Host and plugin(s) are deployed independently, so wire compatibility across
// versions depends entirely on additive changes (new fields get new numbers).

package pluginpb

import (
	context "context"
	commonpb "github.com/seatsurfing/seatsurfing/server/api/commonpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeatsurfingPluginService_GetBasePath_FullMethodName                = "/seatsurfing.plugin.v1.SeatsurfingPluginService/GetBasePath"
	SeatsurfingPluginService_GetRoutePrefix_FullMethodName             = "/seatsurfing.plugin.v1.SeatsurfingPluginService/GetRoutePrefix"
	SeatsurfingPluginService_GetUnauthorizedRoutes_FullMethodName      = "/seatsurfing.plugin.v1.SeatsurfingPluginService/GetUnauthorizedRoutes"
	SeatsurfingPluginService_RunSchemaUpdates_FullMethodName           = "/seatsurfing.plugin.v1.SeatsurfingPluginService/RunSchemaUpdates"
	SeatsurfingPluginService_GetAdminUIMenuItems_FullMethodName        = "/seatsurfing.plugin.v1.SeatsurfingPluginService/GetAdminUIMenuItems"
	SeatsurfingPluginService_OnTimer_FullMethodName                    = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnTimer"
	SeatsurfingPluginService_OnInit_FullMethodName                     = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnInit"
	SeatsurfingPluginService_GetAdminWelcomeScreen_FullMethodName      = "/seatsurfing.plugin.v1.SeatsurfingPluginService/GetAdminWelcomeScreen"
	SeatsurfingPluginService_GetPublicSettings_FullMethodName          = "/seatsurfing.plugin.v1.SeatsurfingPluginService/GetPublicSettings"
	SeatsurfingPluginService_HandleHTTPRequest_FullMethodName          = "/seatsurfing.plugin.v1.SeatsurfingPluginService/HandleHTTPRequest"
	SeatsurfingPluginService_OnUserCreated_FullMethodName              = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnUserCreated"
	SeatsurfingPluginService_OnUserUpdated_FullMethodName              = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnUserUpdated"
	SeatsurfingPluginService_OnBeforeUserDelete_FullMethodName         = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnBeforeUserDelete"
	SeatsurfingPluginService_OnOrganizationCreated_FullMethodName      = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnOrganizationCreated"
	SeatsurfingPluginService_OnOrganizationUpdated_FullMethodName      = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnOrganizationUpdated"
	SeatsurfingPluginService_OnBeforeOrganizationDelete_FullMethodName = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnBeforeOrganizationDelete"
	SeatsurfingPluginService_OnBookingCreated_FullMethodName           = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnBookingCreated"
	SeatsurfingPluginService_OnBookingUpdated_FullMethodName           = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnBookingUpdated"
	SeatsurfingPluginService_OnBookingDeleted_FullMethodName           = "/seatsurfing.plugin.v1.SeatsurfingPluginService/OnBookingDeleted"
)

// SeatsurfingPluginServiceClient is the client API for SeatsurfingPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeatsurfingPluginServiceClient interface {
	// GetBasePath returns the single canonical URL prefix under which all of
	// this plugin's endpoints are nested (e.g. "/cloud-features/"). GetRoutePrefix
	// below still returns the plugin's legacy flat top-level prefixes, which the
	// host keeps mounting alongside the base path for backward compatibility
	// with externally-configured URLs (Stripe webhooks, OAuth redirect URIs,
	// customer SCIM base URLs) that must not break on rollout.
	GetBasePath(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*BasePathReply, error)
	GetRoutePrefix(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*StringListReply, error)
	GetUnauthorizedRoutes(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*StringListReply, error)
	RunSchemaUpdates(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*commonpb.Empty, error)
	GetAdminUIMenuItems(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*AdminUIMenuItemsReply, error)
	OnTimer(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*commonpb.Empty, error)
	// OnInit carries no broker id in gRPC mode - the plugin already knows the
	// host's HostAPI address from its own static config and dials it eagerly
	// at process startup, independent of this call. OnInit must be safe to
	// call more than once: the host re-invokes it on every reconnection.
	OnInit(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*commonpb.Empty, error)
	GetAdminWelcomeScreen(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*AdminWelcomeScreenReply, error)
	GetPublicSettings(ctx context.Context, in *GetPublicSettingsRequest, opts ...grpc.CallOption) (*PluginSettingsReply, error)
	HandleHTTPRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
	OnUserCreated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error)
	OnUserUpdated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error)
	OnBeforeUserDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error)
	OnOrganizationCreated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error)
	OnOrganizationUpdated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error)
	OnBeforeOrganizationDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error)
	OnBookingCreated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error)
	OnBookingUpdated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error)
	OnBookingDeleted(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error)
}

type seatsurfingPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeatsurfingPluginServiceClient(cc grpc.ClientConnInterface) SeatsurfingPluginServiceClient {
	return &seatsurfingPluginServiceClient{cc}
}

func (c *seatsurfingPluginServiceClient) GetBasePath(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*BasePathReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasePathReply)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_GetBasePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) GetRoutePrefix(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*StringListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringListReply)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_GetRoutePrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) GetUnauthorizedRoutes(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*StringListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringListReply)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_GetUnauthorizedRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) RunSchemaUpdates(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_RunSchemaUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) GetAdminUIMenuItems(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*AdminUIMenuItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUIMenuItemsReply)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_GetAdminUIMenuItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnTimer(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnTimer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnInit(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) GetAdminWelcomeScreen(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (*AdminWelcomeScreenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminWelcomeScreenReply)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_GetAdminWelcomeScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) GetPublicSettings(ctx context.Context, in *GetPublicSettingsRequest, opts ...grpc.CallOption) (*PluginSettingsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginSettingsReply)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_GetPublicSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) HandleHTTPRequest(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_HandleHTTPRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnUserCreated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnUserCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnUserUpdated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnUserUpdated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnBeforeUserDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnBeforeUserDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnOrganizationCreated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnOrganizationCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnOrganizationUpdated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnOrganizationUpdated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnBeforeOrganizationDelete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnBeforeOrganizationDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnBookingCreated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnBookingCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnBookingUpdated(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnBookingUpdated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seatsurfingPluginServiceClient) OnBookingDeleted(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*commonpb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.Empty)
	err := c.cc.Invoke(ctx, SeatsurfingPluginService_OnBookingDeleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeatsurfingPluginServiceServer is the server API for SeatsurfingPluginService service.
// All implementations must embed UnimplementedSeatsurfingPluginServiceServer
// for forward compatibility.
type SeatsurfingPluginServiceServer interface {
	// GetBasePath returns the single canonical URL prefix under which all of
	// this plugin's endpoints are nested (e.g. "/cloud-features/"). GetRoutePrefix
	// below still returns the plugin's legacy flat top-level prefixes, which the
	// host keeps mounting alongside the base path for backward compatibility
	// with externally-configured URLs (Stripe webhooks, OAuth redirect URIs,
	// customer SCIM base URLs) that must not break on rollout.
	GetBasePath(context.Context, *commonpb.Empty) (*BasePathReply, error)
	GetRoutePrefix(context.Context, *commonpb.Empty) (*StringListReply, error)
	GetUnauthorizedRoutes(context.Context, *commonpb.Empty) (*StringListReply, error)
	RunSchemaUpdates(context.Context, *commonpb.Empty) (*commonpb.Empty, error)
	GetAdminUIMenuItems(context.Context, *commonpb.Empty) (*AdminUIMenuItemsReply, error)
	OnTimer(context.Context, *commonpb.Empty) (*commonpb.Empty, error)
	// OnInit carries no broker id in gRPC mode - the plugin already knows the
	// host's HostAPI address from its own static config and dials it eagerly
	// at process startup, independent of this call. OnInit must be safe to
	// call more than once: the host re-invokes it on every reconnection.
	OnInit(context.Context, *commonpb.Empty) (*commonpb.Empty, error)
	GetAdminWelcomeScreen(context.Context, *commonpb.Empty) (*AdminWelcomeScreenReply, error)
	GetPublicSettings(context.Context, *GetPublicSettingsRequest) (*PluginSettingsReply, error)
	HandleHTTPRequest(context.Context, *HttpRequest) (*HttpResponse, error)
	OnUserCreated(context.Context, *IdRequest) (*commonpb.Empty, error)
	OnUserUpdated(context.Context, *IdRequest) (*commonpb.Empty, error)
	OnBeforeUserDelete(context.Context, *IdRequest) (*commonpb.Empty, error)
	OnOrganizationCreated(context.Context, *IdRequest) (*commonpb.Empty, error)
	OnOrganizationUpdated(context.Context, *IdRequest) (*commonpb.Empty, error)
	OnBeforeOrganizationDelete(context.Context, *IdRequest) (*commonpb.Empty, error)
	OnBookingCreated(context.Context, *IdRequest) (*commonpb.Empty, error)
	OnBookingUpdated(context.Context, *IdRequest) (*commonpb.Empty, error)
	OnBookingDeleted(context.Context, *IdRequest) (*commonpb.Empty, error)
	mustEmbedUnimplementedSeatsurfingPluginServiceServer()
}

// UnimplementedSeatsurfingPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeatsurfingPluginServiceServer struct{}

func (UnimplementedSeatsurfingPluginServiceServer) GetBasePath(context.Context, *commonpb.Empty) (*BasePathReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBasePath not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) GetRoutePrefix(context.Context, *commonpb.Empty) (*StringListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutePrefix not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) GetUnauthorizedRoutes(context.Context, *commonpb.Empty) (*StringListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnauthorizedRoutes not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) RunSchemaUpdates(context.Context, *commonpb.Empty) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RunSchemaUpdates not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) GetAdminUIMenuItems(context.Context, *commonpb.Empty) (*AdminUIMenuItemsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminUIMenuItems not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnTimer(context.Context, *commonpb.Empty) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnTimer not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnInit(context.Context, *commonpb.Empty) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnInit not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) GetAdminWelcomeScreen(context.Context, *commonpb.Empty) (*AdminWelcomeScreenReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminWelcomeScreen not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) GetPublicSettings(context.Context, *GetPublicSettingsRequest) (*PluginSettingsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicSettings not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) HandleHTTPRequest(context.Context, *HttpRequest) (*HttpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleHTTPRequest not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnUserCreated(context.Context, *IdRequest) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnUserCreated not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnUserUpdated(context.Context, *IdRequest) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnUserUpdated not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnBeforeUserDelete(context.Context, *IdRequest) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnBeforeUserDelete not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnOrganizationCreated(context.Context, *IdRequest) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnOrganizationCreated not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnOrganizationUpdated(context.Context, *IdRequest) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnOrganizationUpdated not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnBeforeOrganizationDelete(context.Context, *IdRequest) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnBeforeOrganizationDelete not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnBookingCreated(context.Context, *IdRequest) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnBookingCreated not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnBookingUpdated(context.Context, *IdRequest) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnBookingUpdated not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) OnBookingDeleted(context.Context, *IdRequest) (*commonpb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnBookingDeleted not implemented")
}
func (UnimplementedSeatsurfingPluginServiceServer) mustEmbedUnimplementedSeatsurfingPluginServiceServer() {
}
func (UnimplementedSeatsurfingPluginServiceServer) testEmbeddedByValue() {}

// UnsafeSeatsurfingPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeatsurfingPluginServiceServer will
// result in compilation errors.
type UnsafeSeatsurfingPluginServiceServer interface {
	mustEmbedUnimplementedSeatsurfingPluginServiceServer()
}

func RegisterSeatsurfingPluginServiceServer(s grpc.ServiceRegistrar, srv SeatsurfingPluginServiceServer) {
	// If the following call panics, it indicates UnimplementedSeatsurfingPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeatsurfingPluginService_ServiceDesc, srv)
}

func _SeatsurfingPluginService_GetBasePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).GetBasePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_GetBasePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).GetBasePath(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_GetRoutePrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).GetRoutePrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_GetRoutePrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).GetRoutePrefix(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_GetUnauthorizedRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).GetUnauthorizedRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_GetUnauthorizedRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).GetUnauthorizedRoutes(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_RunSchemaUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).RunSchemaUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_RunSchemaUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).RunSchemaUpdates(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_GetAdminUIMenuItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).GetAdminUIMenuItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_GetAdminUIMenuItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).GetAdminUIMenuItems(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnTimer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnTimer(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnInit(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_GetAdminWelcomeScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commonpb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).GetAdminWelcomeScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_GetAdminWelcomeScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).GetAdminWelcomeScreen(ctx, req.(*commonpb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_GetPublicSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).GetPublicSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_GetPublicSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).GetPublicSettings(ctx, req.(*GetPublicSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_HandleHTTPRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).HandleHTTPRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_HandleHTTPRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).HandleHTTPRequest(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnUserCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnUserCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnUserCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnUserCreated(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnUserUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnUserUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnUserUpdated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnUserUpdated(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnBeforeUserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnBeforeUserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnBeforeUserDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnBeforeUserDelete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnOrganizationCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnOrganizationCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnOrganizationCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnOrganizationCreated(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnOrganizationUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnOrganizationUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnOrganizationUpdated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnOrganizationUpdated(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnBeforeOrganizationDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnBeforeOrganizationDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnBeforeOrganizationDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnBeforeOrganizationDelete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnBookingCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnBookingCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnBookingCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnBookingCreated(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnBookingUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnBookingUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnBookingUpdated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnBookingUpdated(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeatsurfingPluginService_OnBookingDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeatsurfingPluginServiceServer).OnBookingDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeatsurfingPluginService_OnBookingDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeatsurfingPluginServiceServer).OnBookingDeleted(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeatsurfingPluginService_ServiceDesc is the grpc.ServiceDesc for SeatsurfingPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeatsurfingPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seatsurfing.plugin.v1.SeatsurfingPluginService",
	HandlerType: (*SeatsurfingPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBasePath",
			Handler:    _SeatsurfingPluginService_GetBasePath_Handler,
		},
		{
			MethodName: "GetRoutePrefix",
			Handler:    _SeatsurfingPluginService_GetRoutePrefix_Handler,
		},
		{
			MethodName: "GetUnauthorizedRoutes",
			Handler:    _SeatsurfingPluginService_GetUnauthorizedRoutes_Handler,
		},
		{
			MethodName: "RunSchemaUpdates",
			Handler:    _SeatsurfingPluginService_RunSchemaUpdates_Handler,
		},
		{
			MethodName: "GetAdminUIMenuItems",
			Handler:    _SeatsurfingPluginService_GetAdminUIMenuItems_Handler,
		},
		{
			MethodName: "OnTimer",
			Handler:    _SeatsurfingPluginService_OnTimer_Handler,
		},
		{
			MethodName: "OnInit",
			Handler:    _SeatsurfingPluginService_OnInit_Handler,
		},
		{
			MethodName: "GetAdminWelcomeScreen",
			Handler:    _SeatsurfingPluginService_GetAdminWelcomeScreen_Handler,
		},
		{
			MethodName: "GetPublicSettings",
			Handler:    _SeatsurfingPluginService_GetPublicSettings_Handler,
		},
		{
			MethodName: "HandleHTTPRequest",
			Handler:    _SeatsurfingPluginService_HandleHTTPRequest_Handler,
		},
		{
			MethodName: "OnUserCreated",
			Handler:    _SeatsurfingPluginService_OnUserCreated_Handler,
		},
		{
			MethodName: "OnUserUpdated",
			Handler:    _SeatsurfingPluginService_OnUserUpdated_Handler,
		},
		{
			MethodName: "OnBeforeUserDelete",
			Handler:    _SeatsurfingPluginService_OnBeforeUserDelete_Handler,
		},
		{
			MethodName: "OnOrganizationCreated",
			Handler:    _SeatsurfingPluginService_OnOrganizationCreated_Handler,
		},
		{
			MethodName: "OnOrganizationUpdated",
			Handler:    _SeatsurfingPluginService_OnOrganizationUpdated_Handler,
		},
		{
			MethodName: "OnBeforeOrganizationDelete",
			Handler:    _SeatsurfingPluginService_OnBeforeOrganizationDelete_Handler,
		},
		{
			MethodName: "OnBookingCreated",
			Handler:    _SeatsurfingPluginService_OnBookingCreated_Handler,
		},
		{
			MethodName: "OnBookingUpdated",
			Handler:    _SeatsurfingPluginService_OnBookingUpdated_Handler,
		},
		{
			MethodName: "OnBookingDeleted",
			Handler:    _SeatsurfingPluginService_OnBookingDeleted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
