name: Run UI Tests

on: [pull_request, workflow_dispatch]

jobs:
  container-job:
    name: Run linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: Build TypeScript commons
        working-directory: ./commons/ts
        run: npm ci && npm run build
      - name: Install Booking UI dependencies
        working-directory: ./booking-ui
        run: npm ci
      - name: Run Booking UI linting
        working-directory: ./booking-ui
        run: npm run lint
      - name: Install Admin UI dependencies
        working-directory: ./admin-ui
        run: npm ci
      - name: Run Admin UI linting
        working-directory: ./admin-ui
        run: npm run lint
